from enum import Enum


class StringEnum(str, Enum):
    pass


class AccountStatus(StringEnum):
    PENDING_EMAIL_VERIFICATION = "PENDING_EMAIL_VERIFICATION"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    ACTIVE = "ACTIVE"
    REJECTED = "REJECTED"
    DISABLED = "DISABLED"


class GlobalRole(StringEnum):
    GLOBAL_ADMIN = "GLOBAL_ADMIN"


class WorkspaceKind(StringEnum):
    PERSONAL = "PERSONAL"
    SHARED = "SHARED"


class WorkspaceLifecycle(StringEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class WorkspaceColor(StringEnum):
    GREEN = "GREEN"
    BLUE = "BLUE"
    PURPLE = "PURPLE"
    ORANGE = "ORANGE"
    RED = "RED"
    TEAL = "TEAL"


class WorkspaceIcon(StringEnum):
    HOME = "HOME"
    USERS = "USERS"
    HEART = "HEART"
    STAR = "STAR"
    CALENDAR = "CALENDAR"
    BRIEFCASE = "BRIEFCASE"


class MembershipStatus(StringEnum):
    ACTIVE = "ACTIVE"
    LEFT = "LEFT"
    REMOVED = "REMOVED"


class CalendarVisibility(StringEnum):
    SHOW_DETAILS = "SHOW_DETAILS"
    AVAILABILITY_ONLY = "AVAILABILITY_ONLY"
    HIDE = "HIDE"


class InvitationStatus(StringEnum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class AccountActionTokenType(StringEnum):
    EMAIL_VERIFICATION = "EMAIL_VERIFICATION"
    PASSWORD_RESET = "PASSWORD_RESET"


class GenerationEntityType(StringEnum):
    TASK = "TASK"
    ACTIVITY = "ACTIVITY"


class GenerationPattern(StringEnum):
    DAILY = "DAILY"
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"


class TaskResult(StringEnum):
    COMPLETED = "COMPLETED"
    NOT_COMPLETED = "NOT_COMPLETED"


class HistoryEventType(StringEnum):
    TRACKING = "TRACKING"
    CORRECTION = "CORRECTION"


class ActivityStatus(StringEnum):
    SCHEDULED = "SCHEDULED"
    CANCELLED = "CANCELLED"


class ParticipantCalendarStatus(StringEnum):
    VISIBLE = "VISIBLE"
    REMOVED = "REMOVED"


class ReminderType(StringEnum):
    DAILY_SUMMARY = "DAILY_SUMMARY"
    DAILY_REVIEW = "DAILY_REVIEW"
    PENDING_FOLLOW_UP = "PENDING_FOLLOW_UP"
    PROJECT_FOLLOW_UP = "PROJECT_FOLLOW_UP"
    ACTIVITY_REMINDERS = "ACTIVITY_REMINDERS"


class ScheduleKind(StringEnum):
    DAILY = "DAILY"
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"


class NotificationType(StringEnum):
    WORKSPACE_INVITATION = "WORKSPACE_INVITATION"
    INVITATION_ACCEPTED = "INVITATION_ACCEPTED"
    INVITATION_REJECTED = "INVITATION_REJECTED"
    MEMBER_REMOVED = "MEMBER_REMOVED"
    OWNERSHIP_TRANSFERRED = "OWNERSHIP_TRANSFERRED"
    TASK_ASSIGNED = "TASK_ASSIGNED"
    TASK_REASSIGNED = "TASK_REASSIGNED"
    PENDING_ASSIGNED = "PENDING_ASSIGNED"
    PENDING_REASSIGNED = "PENDING_REASSIGNED"
    PROJECT_LEADER_ASSIGNED = "PROJECT_LEADER_ASSIGNED"
    PROJECT_LEADER_REASSIGNED = "PROJECT_LEADER_REASSIGNED"
    PROJECT_STAGE_ASSIGNED = "PROJECT_STAGE_ASSIGNED"
    PROJECT_STAGE_REASSIGNED = "PROJECT_STAGE_REASSIGNED"
    ACTIVITY_CREATED = "ACTIVITY_CREATED"
    ACTIVITY_UPDATED = "ACTIVITY_UPDATED"
    ACTIVITY_CANCELLED = "ACTIVITY_CANCELLED"
    ACTIVITY_PARTICIPANT_REMOVED = "ACTIVITY_PARTICIPANT_REMOVED"
    DAILY_SUMMARY_REMINDER = "DAILY_SUMMARY_REMINDER"
    DAILY_REVIEW_REMINDER = "DAILY_REVIEW_REMINDER"
    PENDING_FOLLOW_UP_REMINDER = "PENDING_FOLLOW_UP_REMINDER"
    PROJECT_FOLLOW_UP_REMINDER = "PROJECT_FOLLOW_UP_REMINDER"
    ACTIVITY_REMINDER = "ACTIVITY_REMINDER"


class DeliveryStatus(StringEnum):
    PENDING = "PENDING"
    DELIVERED = "DELIVERED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class NotificationJobStatus(StringEnum):
    PENDING = "PENDING"
    SENT = "SENT"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
