import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import * as api from "../../api/v2ProjectApi";
import { TrackingProjectsPage } from "./TrackingProjectsPage";
vi.mock("../../api/v2ProjectApi", () => ({ listV2Projects: vi.fn() }));
const auth = { workspace: { id: "workspace-a", name: "Familia", kind: "SHARED", timezone: "America/Lima" } };
vi.mock("../../hooks/useAuth", () => ({ useAuth: () => auth }));
const project = { id: "project-1", workspace_id: "workspace-a", category_id: "category-1", category_name: "Casa", leader_user_id: "user-1", leader_display_name: "Ana Uno", leader_email: "ana@example.com", name: "Mudanza", description: null, is_active: true, planned_date: null, progress: null, state: null, compliance: null, compliance_detail_days: null, completion_date: null, lock_version: 1, can_edit: true, can_deactivate: true, can_reactivate: false, created_at: "", updated_at: "" };
function mount() { const client = new QueryClient({ defaultOptions: { queries: { retry: false } } }); const view = () => <QueryClientProvider client={client}><TrackingProjectsPage /></QueryClientProvider>; return { ...render(view()), view }; }
describe("V2 TrackingProjectsPage", () => { beforeEach(() => { auth.workspace.id = "workspace-a"; vi.clearAllMocks(); vi.mocked(api.listV2Projects).mockResolvedValue({ items: [project], total: 1, page: 1, page_size: 25, total_pages: 1 }); }); it("is read-only and defers Stage tracking", async () => { mount(); expect(await screen.findByText("Mudanza")).toBeInTheDocument(); expect(screen.getByText(/se habilitará en 7.2/)).toBeInTheDocument(); expect(screen.getByText("Estado: —")).toBeInTheDocument(); expect(screen.queryByRole("button", { name: /guardar/i })).not.toBeInTheDocument(); }); it("isolates Workspace queries", async () => { const mounted = mount(); await screen.findByText("Mudanza"); auth.workspace.id = "workspace-b"; mounted.rerender(mounted.view()); await waitFor(() => expect(api.listV2Projects).toHaveBeenLastCalledWith("workspace-b", { page: 1, page_size: 25, is_active: true })); }); });
