import axios from "axios";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { listAllCategoryOptions } from "../../api/planningPendingItemApi";
import { listAllMasterTasks } from "../../api/planningTaskApi";
import { queryKeys } from "../../api/queryKeys";
import { listTrackingTasks, updateTrackingTaskResult } from "../../api/trackingTaskApi";
import type { PlanningTask, PlanningTaskListParams, PlanningTaskStatus } from "../../types/planningTask";
import type { ReviewTaskResult } from "../../types/review";
import { formatShortCalendarDate } from "../../utils/localizedDate";

const statusLabels: Record<PlanningTaskStatus, string> = { PROGRAMADA: "Programada", PENDIENTE: "Pendiente", COMPLETADA: "Completada", NO_REALIZADA: "No realizada" };
const resultLabels: Record<ReviewTaskResult, string> = { COMPLETED: "Completado", NOT_COMPLETED: "No realizado" };
interface ResultEdit { id: string; name: string; selected: ReviewTaskResult | ""; original: ReviewTaskResult | null; lockVersion: number }

export function TrackingTasksPage() {
  const client = useQueryClient(); const [params, setParams] = useState<PlanningTaskListParams>({ page: 1, page_size: 25 }); const [editing, setEditing] = useState<ResultEdit | null>(null); const [message, setMessage] = useState<{ error: boolean; text: string } | null>(null);
  const masters = useQuery({ queryKey: queryKeys.masterTasks, queryFn: listAllMasterTasks }); const categories = useQuery({ queryKey: queryKeys.categoryOptions, queryFn: listAllCategoryOptions }); const tasks = useQuery({ queryKey: queryKeys.trackingTasks(params), queryFn: () => listTrackingTasks(params) });
  const categoryList = categories.data ?? []; const masterList = masters.data ?? [];
  async function refreshRelated() { await Promise.all([client.invalidateQueries({ queryKey: queryKeys.trackingTasksRoot }), client.invalidateQueries({ queryKey: queryKeys.planningTasksRoot }), client.invalidateQueries({ queryKey: queryKeys.home }), client.invalidateQueries({ queryKey: queryKeys.review }), client.invalidateQueries({ queryKey: queryKeys.taskReportsRoot })]); }
  const save = useMutation({ mutationFn: () => updateTrackingTaskResult(editing!.id, editing!.selected as ReviewTaskResult, editing!.lockVersion), onSuccess: async () => { setEditing(null); setMessage({ error: false, text: "Resultado guardado." }); await refreshRelated(); }, onError: async (error) => { setEditing(null); setMessage({ error: true, text: axios.isAxiosError(error) && error.response?.status === 409 ? "La Tarea cambió desde la última carga. Actualizamos el registro; vuelve a intentarlo." : "No pudimos guardar el resultado de la Tarea." }); await client.invalidateQueries({ queryKey: queryKeys.trackingTasksRoot }); } });
  function beginEdit(task: PlanningTask) { setEditing({ id: task.id, name: task.master_task.name, selected: task.result ?? "", original: task.result, lockVersion: task.lock_version }); setMessage(null); }
  const optionsError = masters.isError || categories.isError; const optionsPending = masters.isPending || categories.isPending;
  const orderedStatuses = useMemo(() => Object.entries(statusLabels) as Array<[PlanningTaskStatus, string]>, []);
  return <section className="tracking-tasks-page"><header><p className="eyebrow">Seguimiento</p><h1>Seguimiento · Tareas</h1></header><section className="tracking-tasks-panel" aria-labelledby="tracking-register"><h2 id="tracking-register">Registro de Tareas</h2>
    {optionsPending ? <p role="status">Cargando opciones…</p> : optionsError ? <div role="alert"><p>No pudimos cargar las opciones de filtro.</p><button type="button" onClick={() => { void masters.refetch(); void categories.refetch(); }}>Reintentar</button></div> : <div className="tracking-task-filters"><label>Desde<input type="date" value={params.planned_from ?? ""} onChange={(event) => setParams({ ...params, page: 1, planned_from: event.target.value || undefined })} /></label><label>Hasta<input type="date" value={params.planned_to ?? ""} onChange={(event) => setParams({ ...params, page: 1, planned_to: event.target.value || undefined })} /></label><label>Tarea<select value={params.master_task_id ?? ""} onChange={(event) => setParams({ ...params, page: 1, master_task_id: event.target.value || undefined })}><option value="">Todas</option>{masterList.map((master) => <option key={master.id} value={master.id}>{master.name}</option>)}</select></label><label>Categoría<select value={params.category_id ?? ""} onChange={(event) => setParams({ ...params, page: 1, category_id: event.target.value || undefined })}><option value="">Todas</option>{categoryList.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Estado<select value={params.status ?? ""} onChange={(event) => setParams({ ...params, page: 1, status: (event.target.value || undefined) as PlanningTaskStatus | undefined })}><option value="">Todos</option>{orderedStatuses.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div>}
    {message ? <p className={message.error ? "review-notice review-notice--error" : "review-notice review-notice--success"} role={message.error ? "alert" : "status"}>{message.text}</p> : null}
    {tasks.isPending ? <p role="status">Cargando Tareas…</p> : tasks.isError ? <div role="alert"><p>No pudimos cargar las Tareas.</p><button type="button" onClick={() => void tasks.refetch()}>Reintentar</button></div> : tasks.data.items.length === 0 ? <p className="review-empty">No hay Tareas para los filtros seleccionados.</p> : <div className="tracking-task-table" role="table" aria-label="Registro de Tareas de Seguimiento"><div className="tracking-task-row tracking-task-row--head" role="row"><span role="columnheader">Fecha</span><span role="columnheader">Tarea</span><span role="columnheader">Categoría</span><span role="columnheader">Estado</span><span role="columnheader">Resultado</span></div>{tasks.data.items.map((task) => <div className="tracking-task-row" role="row" key={task.id}><span role="cell">{formatShortCalendarDate(task.planned_date)}</span><strong role="cell">{task.master_task.name}</strong><span role="cell">{task.master_task.category.name}</span><span role="cell">{statusLabels[task.status]}</span><span role="cell" className="tracking-task-result">{editing?.id === task.id ? <><label><span className="sr-only">Resultado de {task.master_task.name}</span><select aria-label={`Resultado de ${task.master_task.name}`} value={editing.selected} onChange={(event) => setEditing({ ...editing, selected: event.target.value as ReviewTaskResult })}><option value="" disabled>Seleccionar resultado</option>{(Object.entries(resultLabels) as Array<[ReviewTaskResult, string]>).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><button type="button" aria-label={`Guardar resultado de ${task.master_task.name}`} disabled={!editing.selected || editing.selected === editing.original || save.isPending} onClick={() => save.mutate()}>✓</button><button type="button" aria-label={`Cancelar resultado de ${task.master_task.name}`} onClick={() => setEditing(null)}>×</button></> : <>{task.result ? <span>{resultLabels[task.result]}</span> : <span>—</span>}{task.status !== "PROGRAMADA" ? <button type="button" aria-label={`${task.result ? "Corregir" : "Registrar"} resultado de ${task.master_task.name}`} onClick={() => beginEdit(task)}>✎</button> : null}</>}</span></div>)}</div>}
    {tasks.data ? <div className="planning-pagination"><span>Página {tasks.data.page} de {Math.max(1, tasks.data.total_pages)}</span><label>Por página<select value={params.page_size} onChange={(event) => setParams({ ...params, page: 1, page_size: Number(event.target.value) })}>{[25, 50, 100].map((size) => <option key={size}>{size}</option>)}</select></label><button type="button" disabled={params.page <= 1} onClick={() => setParams({ ...params, page: params.page - 1 })}>Anterior</button><button type="button" disabled={params.page >= tasks.data.total_pages} onClick={() => setParams({ ...params, page: params.page + 1 })}>Siguiente</button></div> : null}
  </section></section>;
}
