import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, describe, expect, it, vi } from "vitest";
import * as categoryApi from "../../api/planningPendingItemApi";
import * as masterApi from "../../api/planningTaskApi";
import { queryKeys } from "../../api/queryKeys";
import * as api from "../../api/trackingTaskApi";
import type { PlanningTask, PlanningTaskStatus } from "../../types/planningTask";
import { TrackingTasksPage } from "./TrackingTasksPage";
vi.mock("../../api/trackingTaskApi", () => ({ listTrackingTasks: vi.fn(), updateTrackingTaskResult: vi.fn() })); vi.mock("../../api/planningTaskApi", () => ({ listAllMasterTasks: vi.fn() })); vi.mock("../../api/planningPendingItemApi", () => ({ listAllCategoryOptions: vi.fn() }));
const category = { id: "category", name: "Salud", created_at: "", updated_at: "" }; const master = { id: "master", name: "Correr", category_id: category.id, category, created_at: "", updated_at: "" };
const task = (id: string, status: PlanningTaskStatus, result: PlanningTask["result"]): PlanningTask => ({ id, master_task_id: master.id, planned_date: "2026-08-12", status, result, resolved_at: result ? "2026-08-12T20:00:00Z" : null, resolved_by_id: result ? "user" : null, master_task: master, lock_version: 3, created_at: "", updated_at: "" });
const response = { items: [task("scheduled", "PROGRAMADA", null), task("pending", "PENDIENTE", null), task("completed", "COMPLETADA", "COMPLETED"), task("missed", "NO_REALIZADA", "NOT_COMPLETED")], total: 30, page: 1, page_size: 25, total_pages: 2 };
function renderPage() { const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); const invalidate = vi.spyOn(client, "invalidateQueries"); render(<QueryClientProvider client={client}><TrackingTasksPage /></QueryClientProvider>); return invalidate; }
describe("TrackingTasksPage", () => {
  beforeEach(() => { vi.clearAllMocks(); vi.mocked(masterApi.listAllMasterTasks).mockResolvedValue([master]); vi.mocked(categoryApi.listAllCategoryOptions).mockResolvedValue([category]); vi.mocked(api.listTrackingTasks).mockResolvedValue(response); vi.mocked(api.updateTrackingTaskResult).mockResolvedValue(response.items[2]); });
  it("renders date, MasterTask, Category and all statuses without Planning controls", async () => { renderPage(); const register = await screen.findByRole("table", { name: "Registro de Tareas de Seguimiento" }); for (const value of ["Programada", "Pendiente", "Completada", "No realizada"]) expect(within(register).getByText(value)).toBeInTheDocument(); expect(within(register).getAllByText("Correr")).toHaveLength(4); expect(within(register).getAllByText("Salud")).toHaveLength(4); expect(screen.queryByRole("button", { name: /eliminar|editar fecha/i })).not.toBeInTheDocument(); expect(screen.queryByLabelText(/nueva fecha|seleccionar/i)).not.toBeInTheDocument(); });
  it("protects PROGRAMADA and allows PENDIENTE result entry only after explicit save", async () => { const user = userEvent.setup(); renderPage(); await screen.findByRole("table", { name: "Registro de Tareas de Seguimiento" }); expect(screen.queryByRole("button", { name: "Registrar resultado de Correr" })).toBeInTheDocument(); const buttons = screen.getAllByRole("button", { name: "Registrar resultado de Correr" }); expect(buttons).toHaveLength(1); await user.click(buttons[0]); await user.selectOptions(screen.getByLabelText("Resultado de Correr"), "COMPLETED"); expect(api.updateTrackingTaskResult).not.toHaveBeenCalled(); await user.click(screen.getByRole("button", { name: "Guardar resultado de Correr" })); await waitFor(() => expect(api.updateTrackingTaskResult).toHaveBeenCalledWith("pending", "COMPLETED", 3)); });
  it("corrects either terminal result only to a changed value and supports cancel", async () => { const user = userEvent.setup(); renderPage(); const correctionButtons = await screen.findAllByRole("button", { name: "Corregir resultado de Correr" }); await user.click(correctionButtons[0]); const save = screen.getByRole("button", { name: "Guardar resultado de Correr" }); expect(save).toBeDisabled(); await user.selectOptions(screen.getByLabelText("Resultado de Correr"), "NOT_COMPLETED"); expect(save).toBeEnabled(); await user.click(screen.getByRole("button", { name: "Cancelar resultado de Correr" })); expect(screen.queryByLabelText("Resultado de Correr")).not.toBeInTheDocument(); await user.click(screen.getAllByRole("button", { name: "Corregir resultado de Correr" })[1]); await user.selectOptions(screen.getByLabelText("Resultado de Correr"), "COMPLETED"); await user.click(screen.getByRole("button", { name: "Guardar resultado de Correr" })); await waitFor(() => expect(api.updateTrackingTaskResult).toHaveBeenCalledWith("missed", "COMPLETED", 3)); });
  it("uses all backend filters and shared pagination", async () => { const user = userEvent.setup(); renderPage(); await screen.findByRole("table", { name: "Registro de Tareas de Seguimiento" }); await user.type(screen.getByLabelText("Desde"), "2026-08-01"); await user.type(screen.getByLabelText("Hasta"), "2026-08-31"); await user.selectOptions(screen.getByLabelText("Tarea"), master.id); await user.selectOptions(screen.getByLabelText("Categoría"), category.id); await user.selectOptions(screen.getByLabelText("Estado"), "COMPLETADA"); await waitFor(() => expect(api.listTrackingTasks).toHaveBeenCalledWith(expect.objectContaining({ page: 1, page_size: 25, planned_from: "2026-08-01", planned_to: "2026-08-31", master_task_id: master.id, category_id: category.id, status: "COMPLETADA" }))); const perPage = screen.getByLabelText("Por página"); expect(within(perPage).getAllByRole("option").map((option) => option.textContent)).toEqual(["25", "50", "100"]); await user.click(screen.getByRole("button", { name: "Siguiente" })); await waitFor(() => expect(api.listTrackingTasks).toHaveBeenCalledWith(expect.objectContaining({ page: 2 }))); });
  it("clears stale result state on 409 and refreshes relevant caches", async () => { vi.mocked(api.updateTrackingTaskResult).mockRejectedValue({ isAxiosError: true, response: { status: 409 } }); const user = userEvent.setup(); const invalidate = renderPage(); await user.click((await screen.findAllByRole("button", { name: "Corregir resultado de Correr" }))[0]); await user.selectOptions(screen.getByLabelText("Resultado de Correr"), "NOT_COMPLETED"); await user.click(screen.getByRole("button", { name: "Guardar resultado de Correr" })); expect(await screen.findByRole("alert")).toHaveTextContent("cambió desde la última carga"); expect(screen.queryByLabelText("Resultado de Correr")).not.toBeInTheDocument(); expect(invalidate).toHaveBeenCalledWith({ queryKey: queryKeys.trackingTasksRoot }); });
  it("invalidates Tracking, Planning, Home and Review after success", async () => { const user = userEvent.setup(); const invalidate = renderPage(); await user.click(await screen.findByRole("button", { name: "Registrar resultado de Correr" })); await user.selectOptions(screen.getByLabelText("Resultado de Correr"), "COMPLETED"); await user.click(screen.getByRole("button", { name: "Guardar resultado de Correr" })); await waitFor(() => expect(invalidate).toHaveBeenCalledWith({ queryKey: queryKeys.trackingTasksRoot })); for (const key of [queryKeys.planningTasksRoot, queryKeys.home, queryKeys.review]) expect(invalidate).toHaveBeenCalledWith({ queryKey: key }); });
  it("shows empty and retry states safely", async () => { vi.mocked(api.listTrackingTasks).mockRejectedValueOnce(new Error("network")).mockResolvedValueOnce({ ...response, items: [], total: 0, total_pages: 0 }); const user = userEvent.setup(); renderPage(); expect(await screen.findByRole("alert")).toHaveTextContent("No pudimos cargar las Tareas"); await user.click(screen.getByRole("button", { name: "Reintentar" })); expect(await screen.findByText("No hay Tareas para los filtros seleccionados.")).toHaveClass("review-empty"); });
  it("shows register loading and a safe unexpected mutation error", async () => { let resolveTasks!: (value: typeof response) => void; vi.mocked(api.listTrackingTasks).mockReturnValueOnce(new Promise((resolve) => { resolveTasks = resolve; })); renderPage(); expect(screen.getByText("Cargando Tareas…")).toBeInTheDocument(); resolveTasks(response); const user = userEvent.setup(); await user.click(await screen.findByRole("button", { name: "Registrar resultado de Correr" })); await user.selectOptions(screen.getByLabelText("Resultado de Correr"), "COMPLETED"); vi.mocked(api.updateTrackingTaskResult).mockRejectedValueOnce(new Error("network")); await user.click(screen.getByRole("button", { name: "Guardar resultado de Correr" })); expect(await screen.findByRole("alert")).toHaveTextContent("No pudimos guardar el resultado de la Tarea."); });
});
