import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { queryKeys } from "../../api/queryKeys";
import { listV2Projects } from "../../api/v2ProjectApi";
import { useAuth } from "../../hooks/useAuth";
import type { V2ProjectFilters } from "../../types/v2Project";

export function TrackingProjectsPage() { const { workspace } = useAuth(); if (!workspace) return <section><h1>Seguimiento · Proyectos</h1><p>Selecciona un espacio.</p></section>; return <WorkspaceTrackingProjects key={workspace.id} workspaceId={workspace.id} />; }
function WorkspaceTrackingProjects({ workspaceId }: { workspaceId: string }) { const [filters, setFilters] = useState<V2ProjectFilters>({ page: 1, page_size: 25, is_active: true }); const projects = useQuery({ queryKey: queryKeys.v2Projects(workspaceId, filters), queryFn: () => listV2Projects(workspaceId, filters) }); return <section className="v2-project-page"><header><p className="eyebrow">Seguimiento</p><h1>Seguimiento · Proyectos</h1><p>El avance, Estado y Cumplimiento se derivan de las Etapas.</p></header><label>Buscar<input type="search" value={filters.search ?? ""} onChange={(event) => setFilters({ ...filters, page: 1, search: event.target.value || undefined })} /></label>{projects.isPending ? <p role="status">Cargando Proyectos…</p> : projects.isError ? <div role="alert"><p>No pudimos cargar los Proyectos.</p><button type="button" onClick={() => void projects.refetch()}>Reintentar</button></div> : projects.data.items.length === 0 ? <p className="review-empty">No existen Proyectos activos.</p> : <div className="v2-project-list">{projects.data.items.map((project) => <article key={project.id} className="v2-project-row"><div><strong>{project.name}</strong><small>{project.category_name} · {project.leader_display_name}</small></div>{project.weights_complete ? <><span>Avance: {project.progress}%</span><span>Estado: {project.state}</span><span>Cumplimiento: {project.compliance ?? "—"}</span></> : <span>{project.stage_count === 0 ? "Sin Etapas · Avance 0%" : `Pesos incompletos: ${project.total_weight}%`}</span>}</article>)}</div>}</section>; }
