import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, describe, expect, it, vi } from "vitest";
import * as api from "../../api/masterDataApi";
import * as optionsApi from "../../api/planningPendingItemApi";
import { queryKeys } from "../../api/queryKeys";
import { CategoriesTablePage } from "./CategoriesTablePage";
import { MasterTasksTablePage } from "./MasterTasksTablePage";
vi.mock("../../api/masterDataApi", () => ({ listCategoryTable: vi.fn(), createCategoryTable: vi.fn(), updateCategoryTable: vi.fn(), deleteCategoryTable: vi.fn(), listMasterTaskTable: vi.fn(), createMasterTaskTable: vi.fn(), updateMasterTaskTable: vi.fn(), deleteMasterTaskTable: vi.fn() }));
vi.mock("../../api/planningPendingItemApi", () => ({ listAllCategoryOptions: vi.fn() }));
const category = { id: "category-1", name: "Personal", created_at: "", updated_at: "" }; const master = { id: "master-1", name: "Salir a correr", category_id: category.id, category, created_at: "", updated_at: "" };
function renderWithClient(node: React.ReactNode) { const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); const invalidate = vi.spyOn(client, "invalidateQueries"); render(<QueryClientProvider client={client}>{node}</QueryClientProvider>); return invalidate; }
describe("CategoriesTablePage", () => {
  beforeEach(() => { vi.clearAllMocks(); vi.mocked(api.listCategoryTable).mockResolvedValue({ items: [category], total: 26, page: 1, page_size: 25, total_pages: 2 }); vi.mocked(api.createCategoryTable).mockResolvedValue(category); vi.mocked(api.updateCategoryTable).mockResolvedValue(category); vi.mocked(api.deleteCategoryTable).mockResolvedValue(); vi.spyOn(window, "confirm").mockReturnValue(true); });
  it("creates, edits and deletes with compact accessible actions", async () => { const user = userEvent.setup(); renderWithClient(<CategoriesTablePage />); const register = await screen.findByRole("table", { name: "Registro de Categorías" }); const createSection = screen.getByRole("heading", { name: "Crear Categoría" }).closest<HTMLElement>("section")!; await user.type(within(createSection).getByLabelText("Nombre"), "Casa"); await user.click(within(createSection).getByRole("button", { name: "Crear" })); await waitFor(() => expect(api.createCategoryTable).toHaveBeenCalledWith("Casa")); await user.click(within(register).getByRole("button", { name: "Editar Categoría Personal" })); await user.clear(screen.getByLabelText("Nombre de Categoría Personal")); await user.type(screen.getByLabelText("Nombre de Categoría Personal"), "Familia"); await user.click(screen.getByRole("button", { name: "Guardar Categoría Personal" })); await waitFor(() => expect(api.updateCategoryTable).toHaveBeenCalledWith("category-1", "Familia")); await user.click(await screen.findByRole("button", { name: "Eliminar Categoría Personal" })); expect(window.confirm).toHaveBeenCalledWith('¿Eliminar la Categoría "Personal"?'); await waitFor(() => expect(api.deleteCategoryTable).toHaveBeenCalledWith("category-1")); });
  it("handles used-category 409, clears editing and refreshes dependent caches", async () => { vi.mocked(api.updateCategoryTable).mockRejectedValue({ isAxiosError: true, response: { status: 409, data: { detail: "Category is already in use" } } }); const user = userEvent.setup(); const invalidate = renderWithClient(<CategoriesTablePage />); await user.click(await screen.findByRole("button", { name: "Editar Categoría Personal" })); await user.click(screen.getByRole("button", { name: "Guardar Categoría Personal" })); expect(await screen.findByRole("alert")).toHaveTextContent("ya fue utilizada"); expect(screen.queryByLabelText("Nombre de Categoría Personal")).not.toBeInTheDocument(); for (const key of [queryKeys.categoryTableRoot, queryKeys.categoryOptions, queryKeys.taskReportsRoot, queryKeys.pendingItemReportsRoot, queryKeys.projectReportsRoot]) expect(invalidate).toHaveBeenCalledWith({ queryKey: key }); });
  it("uses the shared pagination options and empty state", async () => { vi.mocked(api.listCategoryTable).mockResolvedValue({ items: [], total: 0, page: 1, page_size: 25, total_pages: 0 }); renderWithClient(<CategoriesTablePage />); expect(await screen.findByText("Aún no hay Categorías.")).toHaveClass("review-empty"); const perPage = screen.getByLabelText("Por página"); expect(within(perPage).getAllByRole("option").map((option) => option.textContent)).toEqual(["25", "50", "100"]); });
});
describe("MasterTasksTablePage", () => {
  beforeEach(() => { vi.clearAllMocks(); vi.mocked(optionsApi.listAllCategoryOptions).mockResolvedValue([category]); vi.mocked(api.listMasterTaskTable).mockResolvedValue({ items: [master], total: 1, page: 1, page_size: 25, total_pages: 1 }); vi.mocked(api.createMasterTaskTable).mockResolvedValue(master); vi.mocked(api.updateMasterTaskTable).mockResolvedValue(master); vi.mocked(api.deleteMasterTaskTable).mockResolvedValue(); vi.spyOn(window, "confirm").mockReturnValue(true); });
  it("creates and filters using configured Categories only", async () => { const user = userEvent.setup(); renderWithClient(<MasterTasksTablePage />); const createSection = screen.getByRole("heading", { name: "Crear Tarea" }).closest<HTMLElement>("section")!; await within(createSection).findByRole("option", { name: "Personal" }); await user.type(within(createSection).getByLabelText("Nombre"), "Leer"); await user.selectOptions(within(createSection).getByLabelText("Categoría"), category.id); await user.click(within(createSection).getByRole("button", { name: "Crear" })); await waitFor(() => expect(api.createMasterTaskTable).toHaveBeenCalledWith("Leer", category.id)); const register = screen.getByRole("heading", { name: "Registro de Tareas" }).closest<HTMLElement>("section")!; await user.selectOptions(within(register).getByLabelText("Categoría"), category.id); await waitFor(() => expect(api.listMasterTaskTable).toHaveBeenCalledWith(expect.objectContaining({ page: 1, page_size: 25, category_id: category.id }))); expect(screen.queryByLabelText(/fecha|recurrencia|prioridad|descripción/i)).not.toBeInTheDocument(); });
  it("edits/deletes and invalidates Planning options and Task Reports", async () => { const user = userEvent.setup(); const invalidate = renderWithClient(<MasterTasksTablePage />); await user.click(await screen.findByRole("button", { name: "Editar Tarea Salir a correr" })); await user.clear(screen.getByLabelText("Nombre de Tarea Salir a correr")); await user.type(screen.getByLabelText("Nombre de Tarea Salir a correr"), "Caminar"); await user.click(screen.getByRole("button", { name: "Guardar Tarea Salir a correr" })); await waitFor(() => expect(api.updateMasterTaskTable).toHaveBeenCalledWith("master-1", "Caminar", "category-1")); expect(invalidate).toHaveBeenCalledWith({ queryKey: queryKeys.masterTasks }); expect(invalidate).toHaveBeenCalledWith({ queryKey: queryKeys.taskReportsRoot }); await user.click(await screen.findByRole("button", { name: "Eliminar Tarea Salir a correr" })); await waitFor(() => expect(api.deleteMasterTaskTable).toHaveBeenCalledWith("master-1")); });
  it("handles immutable 409 without keeping stale edit state", async () => { vi.mocked(api.updateMasterTaskTable).mockRejectedValue({ isAxiosError: true, response: { status: 409, data: { detail: "Master task is already in use" } } }); const user = userEvent.setup(); renderWithClient(<MasterTasksTablePage />); await user.click(await screen.findByRole("button", { name: "Editar Tarea Salir a correr" })); await user.click(screen.getByRole("button", { name: "Guardar Tarea Salir a correr" })); expect(await screen.findByRole("alert")).toHaveTextContent("ya fue utilizada"); expect(screen.queryByLabelText("Nombre de Tarea Salir a correr")).not.toBeInTheDocument(); });
  it("prevents creation when no Categories exist", async () => { vi.mocked(optionsApi.listAllCategoryOptions).mockResolvedValue([]); renderWithClient(<MasterTasksTablePage />); expect(await screen.findByText("Aún no hay Categorías configuradas en Tablas > Categorías.")).toBeInTheDocument(); expect(screen.queryByRole("button", { name: "Crear" })).not.toBeInTheDocument(); });
});
