import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { useMemo, useState, type PropsWithChildren } from "react";
import { MemoryRouter } from "react-router-dom";
import { beforeEach, describe, expect, it, vi } from "vitest";

import * as categoryApi from "../../api/categoryApi";
import * as projectApi from "../../api/projectApi";
import * as seriesApi from "../../api/taskSeriesApi";
import * as workspaceApi from "../../api/workspaceApi";
import { useAuth } from "../../hooks/useAuth";
import { AuthContext, type AuthState } from "../../store/auth-context";
import { testUser } from "../../test/testUser";
import type { WorkspaceSummary } from "../../types/auth";
import type { TaskSeries } from "../../types/taskSeries";
import { RecurringTasksPage } from "./RecurringTasksPage";

vi.mock("../../api/workspaceApi", () => ({ listWorkspaces: vi.fn() }));
vi.mock("../../api/categoryApi", () => ({ listCategories: vi.fn() }));
vi.mock("../../api/projectApi", () => ({ listProjects: vi.fn() }));
vi.mock("../../api/taskSeriesApi", () => ({ listTaskSeries: vi.fn(), createTaskSeries: vi.fn(), updateTaskSeries: vi.fn(), activateTaskSeries: vi.fn(), deactivateTaskSeries: vi.fn(), materializeTaskSeries: vi.fn(), synchronizeTaskSeries: vi.fn() }));

const workspace: WorkspaceSummary = { id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa", name: "Personal", description: null, timezone: "America/Lima", created_at: "2026-08-01T00:00:00Z", updated_at: "2026-08-01T00:00:00Z" };
const otherWorkspace = { ...workspace, id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb", name: "Trabajo" };
const category = { id: "cccccccc-cccc-4ccc-8ccc-cccccccccccc", workspace_id: workspace.id, name: "Rutinas", description: null, is_active: true, created_at: "2026-08-01T00:00:00Z", updated_at: "2026-08-01T00:00:00Z" };
const project = { id: "dddddddd-dddd-4ddd-8ddd-dddddddddddd", workspace_id: workspace.id, name: "Bienestar", description: null, is_active: true, created_at: "2026-08-01T00:00:00Z", updated_at: "2026-08-01T00:00:00Z" };
const series: TaskSeries = { id: "11111111-1111-4111-8111-111111111111", workspace_id: workspace.id, created_by_id: testUser.id, category_id: category.id, project_id: project.id, title: "Revisión semanal", description: "Planificar próximos pasos", timezone: "America/Lima", frequency: "weekly", interval: 1, weekdays: [0, 2, 4], month_day: null, starts_at: "2026-08-03T13:00:00Z", ends_at: "2026-12-31T13:00:00Z", is_active: true, created_at: "2026-08-01T00:00:00Z", updated_at: "2026-08-01T00:00:00Z" };

function Auth({ children, initial = workspace }: PropsWithChildren<{ initial?: WorkspaceSummary | null }>) { const [selected, setWorkspace] = useState(initial); const value = useMemo<AuthState>(() => ({ accessToken: "token", user: testUser, workspace: selected, isAuthenticated: true, isInitializing: false, login: vi.fn(), logout: vi.fn(), setWorkspace, clearSession: vi.fn() }), [selected]); return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>; }
function Switcher() { const { setWorkspace } = useAuth(); return <button onClick={() => setWorkspace(otherWorkspace)}>Cambiar espacio</button>; }
function renderPage(initial: WorkspaceSummary | null = workspace, switcher = false) { const client = new QueryClient({ defaultOptions: { queries: { retry: false, gcTime: Infinity }, mutations: { retry: false } } }); render(<QueryClientProvider client={client}><Auth initial={initial}><MemoryRouter>{switcher && <Switcher />}<RecurringTasksPage /></MemoryRouter></Auth></QueryClientProvider>); return client; }

describe("RecurringTasksPage", () => {
  beforeEach(() => { vi.clearAllMocks(); vi.mocked(workspaceApi.listWorkspaces).mockResolvedValue([workspace]); vi.mocked(categoryApi.listCategories).mockResolvedValue([category]); vi.mocked(projectApi.listProjects).mockResolvedValue([project]); vi.mocked(seriesApi.listTaskSeries).mockResolvedValue({ items: [series], total: 1 }); vi.mocked(seriesApi.createTaskSeries).mockResolvedValue(series); vi.mocked(seriesApi.updateTaskSeries).mockResolvedValue(series); vi.mocked(seriesApi.activateTaskSeries).mockResolvedValue({ ...series, is_active: true }); vi.mocked(seriesApi.deactivateTaskSeries).mockResolvedValue({ ...series, is_active: false }); vi.mocked(seriesApi.materializeTaskSeries).mockResolvedValue({ generated_count: 2, generated_task_ids: ["1", "2"] }); vi.mocked(seriesApi.synchronizeTaskSeries).mockResolvedValue({ created_count: 1, updated_count: 2, deleted_count: 3, created_task_ids: [], updated_task_ids: [], deleted_task_ids: [] }); });

  it("loads the selected Workspace series and renders its Spanish recurrence summary", async () => { renderPage(); expect(await screen.findByRole("heading", { name: series.title })).toBeInTheDocument(); expect(screen.getByText(/Cada semana: lunes, miércoles, viernes a las 08:00/)).toBeInTheDocument(); expect(seriesApi.listTaskSeries).toHaveBeenCalledWith(workspace.id, null); });
  it("does not call scoped APIs without a Workspace", async () => { vi.mocked(workspaceApi.listWorkspaces).mockResolvedValue([]); renderPage(null); expect(await screen.findByText("No hay un espacio de trabajo disponible")).toBeInTheDocument(); expect(seriesApi.listTaskSeries).not.toHaveBeenCalled(); expect(categoryApi.listCategories).not.toHaveBeenCalled(); });
  it("isolates queries when switching Workspaces", async () => { vi.mocked(workspaceApi.listWorkspaces).mockResolvedValue([workspace, otherWorkspace]); const user = userEvent.setup(); renderPage(workspace, true); await screen.findByRole("heading", { name: series.title }); await user.click(screen.getByRole("button", { name: "Cambiar espacio" })); await waitFor(() => expect(seriesApi.listTaskSeries).toHaveBeenCalledWith(otherWorkspace.id, null)); });
  it("maps active and inactive lifecycle filters", async () => { const user = userEvent.setup(); renderPage(); await screen.findByRole("heading", { name: series.title }); await user.click(screen.getByRole("button", { name: "Activas" })); await waitFor(() => expect(seriesApi.listTaskSeries).toHaveBeenLastCalledWith(workspace.id, true)); await user.click(screen.getByRole("button", { name: "Inactivas" })); await waitFor(() => expect(seriesApi.listTaskSeries).toHaveBeenLastCalledWith(workspace.id, false)); });
  it("shows loading, empty, and retryable error states", async () => { vi.mocked(seriesApi.listTaskSeries).mockReturnValueOnce(new Promise(() => undefined)); renderPage(); expect(await screen.findByRole("status", { name: "Cargando tareas recurrentes" })).toBeInTheDocument(); });
  it("renders an actionable empty state", async () => { vi.mocked(seriesApi.listTaskSeries).mockResolvedValue({ items: [], total: 0 }); renderPage(); expect(await screen.findByText("Aún no tienes tareas recurrentes.")).toBeInTheDocument(); expect(screen.getByRole("button", { name: "Crear primera recurrencia" })).toBeInTheDocument(); });
  it("retries list failures", async () => { vi.mocked(seriesApi.listTaskSeries).mockRejectedValueOnce(new Error("offline")).mockResolvedValueOnce({ items: [series], total: 1 }); const user = userEvent.setup(); renderPage(); expect(await screen.findByText("No pudimos cargar las tareas recurrentes.")).toBeInTheDocument(); await user.click(screen.getByRole("button", { name: "Reintentar" })); expect(await screen.findByRole("heading", { name: series.title })).toBeInTheDocument(); });

  it("validates create and submits a daily recurrence using Workspace timezone", async () => { const user = userEvent.setup(); renderPage(); await screen.findByRole("heading", { name: series.title }); await user.click(screen.getByRole("button", { name: "Nueva recurrencia" })); const dialog = screen.getByRole("dialog"); expect(within(dialog).getByLabelText("Zona horaria IANA")).toHaveValue(workspace.timezone); await user.click(within(dialog).getByRole("button", { name: "Guardar recurrencia" })); expect(await within(dialog).findByText("Ingresa un título.")).toBeInTheDocument(); await user.type(within(dialog).getByLabelText("Título"), "Rutina diaria"); await user.type(within(dialog).getByLabelText("Inicio local"), "2026-08-10T08:00"); await user.click(within(dialog).getByRole("button", { name: "Guardar recurrencia" })); await waitFor(() => expect(seriesApi.createTaskSeries).toHaveBeenCalledWith(workspace.id, expect.objectContaining({ title: "Rutina diaria", frequency: "daily", timezone: "America/Lima", starts_at: "2026-08-10T13:00:00.000Z", weekdays: null, month_day: null }))); });
  it("creates weekly and monthly recurrence shapes", async () => { const user = userEvent.setup(); renderPage(); await screen.findByRole("heading", { name: series.title }); await user.click(screen.getByRole("button", { name: "Nueva recurrencia" })); let dialog = screen.getByRole("dialog"); await user.type(within(dialog).getByLabelText("Título"), "Semanal"); await user.type(within(dialog).getByLabelText("Inicio local"), "2026-08-10T08:00"); await user.selectOptions(within(dialog).getByLabelText("Frecuencia"), "weekly"); await user.click(within(dialog).getByLabelText("lunes")); await user.click(within(dialog).getByRole("button", { name: "Guardar recurrencia" })); await waitFor(() => expect(seriesApi.createTaskSeries).toHaveBeenCalledWith(workspace.id, expect.objectContaining({ frequency: "weekly", weekdays: [0] }))); await user.click(screen.getByRole("button", { name: "Nueva recurrencia" })); dialog = screen.getByRole("dialog"); await user.type(within(dialog).getByLabelText("Título"), "Mensual"); await user.type(within(dialog).getByLabelText("Inicio local"), "2026-08-10T08:00"); await user.selectOptions(within(dialog).getByLabelText("Frecuencia"), "monthly"); await user.type(within(dialog).getByLabelText("Día del mes"), "15"); await user.click(within(dialog).getByRole("button", { name: "Guardar recurrencia" })); await waitFor(() => expect(seriesApi.createTaskSeries).toHaveBeenLastCalledWith(workspace.id, expect.objectContaining({ frequency: "monthly", month_day: 15, weekdays: null }))); });

  it("prefills editing, clears associations, and never synchronizes automatically", async () => { const user = userEvent.setup(); renderPage(); await screen.findByRole("heading", { name: series.title }); await user.click(screen.getByRole("button", { name: `Editar ${series.title}` })); const dialog = screen.getByRole("dialog"); expect(within(dialog).getByLabelText("Título")).toHaveValue(series.title); expect(within(dialog).getByLabelText("Categoría")).toHaveValue(category.id); await user.selectOptions(within(dialog).getByLabelText("Categoría"), ""); await user.selectOptions(within(dialog).getByLabelText("Proyecto"), ""); await user.click(within(dialog).getByRole("button", { name: "Guardar recurrencia" })); await waitFor(() => expect(seriesApi.updateTaskSeries).toHaveBeenCalledWith(workspace.id, series.id, expect.objectContaining({ category_id: null, project_id: null }))); expect(seriesApi.synchronizeTaskSeries).not.toHaveBeenCalled(); expect(await screen.findByText(/Usa Sincronizar/)).toBeInTheDocument(); });
  it("preserves inactive existing associations while blocking new inactive assignment", async () => { vi.mocked(categoryApi.listCategories).mockResolvedValue([{ ...category, is_active: false }]); const user = userEvent.setup(); renderPage(); await screen.findByRole("heading", { name: series.title }); await user.click(screen.getByRole("button", { name: `Editar ${series.title}` })); const option = within(screen.getByRole("dialog")).getByRole("option", { name: "Rutinas (inactiva)" }); expect(option).toBeEnabled(); expect(within(screen.getByRole("dialog")).getByLabelText("Categoría")).toHaveValue(category.id); });
  it("supports idempotent activation and deactivation endpoints", async () => { const user = userEvent.setup(); renderPage(); await screen.findByRole("heading", { name: series.title }); await user.click(screen.getByRole("button", { name: `Desactivar ${series.title}` })); await waitFor(() => expect(seriesApi.deactivateTaskSeries).toHaveBeenCalledWith(workspace.id, series.id)); });

  it("validates and materializes a window, including zero-result messaging", async () => { const user = userEvent.setup(); renderPage(); await screen.findByRole("heading", { name: series.title }); await user.click(screen.getByRole("button", { name: `Materializar ${series.title}` })); let dialog = screen.getByRole("dialog"); await user.click(within(dialog).getByRole("button", { name: "Materializar" })); expect(await within(dialog).findByText("Selecciona el inicio.")).toBeInTheDocument(); await user.type(within(dialog).getByLabelText(/Inicio/), "2026-08-10T00:00"); await user.type(within(dialog).getByLabelText(/Fin/), "2026-08-17T23:59"); await user.click(within(dialog).getByRole("button", { name: "Materializar" })); expect(await screen.findByText("Se generaron 2 tareas.")).toBeInTheDocument(); vi.mocked(seriesApi.materializeTaskSeries).mockResolvedValue({ generated_count: 0, generated_task_ids: [] }); await user.click(screen.getByRole("button", { name: `Materializar ${series.title}` })); dialog = screen.getByRole("dialog"); await user.type(within(dialog).getByLabelText(/Inicio/), "2026-08-10T00:00"); await user.type(within(dialog).getByLabelText(/Fin/), "2026-08-17T23:59"); await user.click(within(dialog).getByRole("button", { name: "Materializar" })); expect(await screen.findByText("No había nuevas tareas por generar en ese rango.")).toBeInTheDocument(); });
  it("summarizes synchronization and invalidates only current Workspace task/dashboard caches", async () => { const user = userEvent.setup(); const client = renderPage(); const invalidate = vi.spyOn(client, "invalidateQueries"); await screen.findByRole("heading", { name: series.title }); await user.click(screen.getByRole("button", { name: `Sincronizar ${series.title}` })); const dialog = screen.getByRole("dialog"); expect(within(dialog).getByText(/tareas futuras no resueltas/)).toBeInTheDocument(); await user.type(within(dialog).getByLabelText(/Inicio/), "2026-08-10T00:00"); await user.type(within(dialog).getByLabelText(/Fin/), "2026-08-17T23:59"); await user.click(within(dialog).getByRole("button", { name: "Sincronizar" })); expect(await screen.findByText("Sincronización completada: 1 creadas, 2 actualizadas y 3 eliminadas.")).toBeInTheDocument(); expect(invalidate).toHaveBeenCalledWith({ queryKey: ["tasks", workspace.id] }); expect(invalidate).toHaveBeenCalledWith({ queryKey: ["dashboard", "summary", workspace.id] }); expect(invalidate).not.toHaveBeenCalledWith({ queryKey: ["tasks", otherWorkspace.id] }); });
  it("shows safe materialization and synchronization conflicts", async () => { vi.mocked(seriesApi.materializeTaskSeries).mockRejectedValue({ isAxiosError: true, response: { status: 409 } }); const user = userEvent.setup(); renderPage(); await screen.findByRole("heading", { name: series.title }); await user.click(screen.getByRole("button", { name: `Materializar ${series.title}` })); const dialog = screen.getByRole("dialog"); await user.type(within(dialog).getByLabelText(/Inicio/), "2026-08-10T00:00"); await user.type(within(dialog).getByLabelText(/Fin/), "2026-08-17T23:59"); await user.click(within(dialog).getByRole("button", { name: "Materializar" })); expect(await within(dialog).findByRole("alert")).toHaveTextContent("Revisa el rango"); });
});
