import { beforeEach, describe, expect, it, vi } from "vitest";
import { apiClient } from "./client";
import * as api from "./masterDataApi";
vi.mock("./client", () => ({ apiClient: { get: vi.fn(), post: vi.fn(), patch: vi.fn(), delete: vi.fn() } }));
describe("masterDataApi", () => {
  beforeEach(() => vi.clearAllMocks());
  it("uses exact Category endpoints and payloads without workspace_id", async () => { vi.mocked(apiClient.get).mockResolvedValue({ data: {} }); vi.mocked(apiClient.post).mockResolvedValue({ data: {} }); vi.mocked(apiClient.patch).mockResolvedValue({ data: {} }); vi.mocked(apiClient.delete).mockResolvedValue({}); await api.listCategoryTable({ page: 1, page_size: 25 }); expect(apiClient.get).toHaveBeenCalledWith("http://localhost:8000/api/v1/categories", { params: { page: 1, page_size: 25 } }); await api.createCategoryTable("Personal"); expect(apiClient.post).toHaveBeenCalledWith("http://localhost:8000/api/v1/categories", { name: "Personal" }); await api.updateCategoryTable("category", "Casa"); expect(apiClient.patch).toHaveBeenCalledWith("http://localhost:8000/api/v1/categories/category", { name: "Casa" }); await api.deleteCategoryTable("category"); expect(apiClient.delete).toHaveBeenCalledWith("http://localhost:8000/api/v1/categories/category"); });
  it("uses exact Master Task endpoints and name/category-only payloads", async () => { vi.mocked(apiClient.get).mockResolvedValue({ data: {} }); vi.mocked(apiClient.post).mockResolvedValue({ data: {} }); vi.mocked(apiClient.patch).mockResolvedValue({ data: {} }); vi.mocked(apiClient.delete).mockResolvedValue({}); const params = { page: 1, page_size: 25, category_id: "category" }; await api.listMasterTaskTable(params); expect(apiClient.get).toHaveBeenCalledWith("http://localhost:8000/api/v1/master-tasks", { params }); await api.createMasterTaskTable("Correr", "category"); expect(apiClient.post).toHaveBeenCalledWith("http://localhost:8000/api/v1/master-tasks", { name: "Correr", category_id: "category" }); await api.updateMasterTaskTable("master", "Caminar", "category"); expect(apiClient.patch).toHaveBeenCalledWith("http://localhost:8000/api/v1/master-tasks/master", { name: "Caminar", category_id: "category" }); await api.deleteMasterTaskTable("master"); expect(apiClient.delete).toHaveBeenCalledWith("http://localhost:8000/api/v1/master-tasks/master"); });
});
