export const queryKeys = {
  notificationPreferences: ["v2-notification-preferences"] as const,
  v2Home: ["v2-home"] as const,
  myCalendar: (userId: string, rangeStart: string, rangeEnd: string, projection = "DETAIL", workspaceId = "ALL") => ["calendar-me", userId, rangeStart, rangeEnd, projection, workspaceId] as const,
  myCalendarRoot: (userId: string) => ["calendar-me", userId] as const,
  calendarComparison: (viewerId: string, workspaceId: string, targetUserId: string, rangeStart: string, rangeEnd: string) => ["calendar-comparison", viewerId, workspaceId, targetUserId, rangeStart, rangeEnd] as const,
  calendarComparisonRoot: (viewerId: string, workspaceId: string) => ["calendar-comparison", viewerId, workspaceId] as const,
  calendarVisibility: (viewerId: string, workspaceId: string) => ["calendar-visibility", viewerId, workspaceId] as const,
  v2Tasks: (workspaceId: string, params: object) => ["v2-tasks", workspaceId, params] as const,
  v2TasksRoot: (workspaceId: string) => ["v2-tasks", workspaceId] as const,
  v2PendingItems: (workspaceId: string, filters: object) => ["v2-pending-items", workspaceId, filters] as const,
  v2PendingItemsRoot: (workspaceId: string) => ["v2-pending-items", workspaceId] as const,
  v2PendingItemDetail: (workspaceId: string, itemId: string) => ["v2-pending-items", workspaceId, "detail", itemId] as const,
  v2PendingItemHistory: (workspaceId: string, itemId: string) => ["v2-pending-items", workspaceId, "history", itemId] as const,
  v2Projects: (workspaceId: string, filters: object) => ["v2-projects", workspaceId, filters] as const,
  v2ProjectsRoot: (workspaceId: string) => ["v2-projects", workspaceId] as const,
  v2ProjectDetail: (workspaceId: string, projectId: string) => ["v2-projects", workspaceId, "detail", projectId] as const,
  v2ProjectStages: (workspaceId: string, projectId: string) => ["v2-projects", workspaceId, "detail", projectId, "stages"] as const,
  v2ProjectStageDetail: (workspaceId: string, projectId: string, stageId: string) => ["v2-projects", workspaceId, "detail", projectId, "stages", stageId] as const,
  v2ProjectStageHistory: (workspaceId: string, projectId: string, stageId: string) => ["v2-projects", workspaceId, "detail", projectId, "stages", stageId, "history"] as const,
  v2Activities: (workspaceId: string, filters: object) => ["v2-activities", workspaceId, filters] as const,
  v2ActivitiesRoot: (workspaceId: string) => ["v2-activities", workspaceId] as const,
  v2Catalog: (workspaceId: string, kind: string, params: object) => ["v2-catalog", workspaceId, kind, params] as const,
  v2CatalogRoot: (workspaceId: string) => ["v2-catalog", workspaceId] as const,
  v2CatalogSelector: (workspaceId: string, kind: string, currentId?: string, search?: string) => ["v2-catalog-selector", workspaceId, kind, currentId, search] as const,
  v2CatalogSelectorRoot: (workspaceId: string) => ["v2-catalog-selector", workspaceId] as const,
  v2ReportSummary: (workspaceId: string, filters: object) => ["v2-reports", workspaceId, "summary", filters] as const,
  home: ["home"] as const,
  review: ["review"] as const,
  masterTasks: ["master-tasks", "options"] as const,
  planningTasks: (params: object) => ["tasks", "planning", params] as const,
  planningTasksRoot: ["tasks", "planning"] as const,
  categoryOptions: ["categories", "options"] as const,
  planningPendingItems: (params: object) => ["pending-items", "planning", params] as const,
  planningPendingItemsRoot: ["pending-items", "planning"] as const,
  planningProjects: (params: object) => ["projects", "planning", params] as const,
  planningProjectsRoot: ["projects", "planning"] as const,
  planningProjectDetail: (id: string) => ["projects", "planning", "detail", id] as const,
  categoryTable: (params: object) => ["categories", "table", params] as const,
  categoryTableRoot: ["categories", "table"] as const,
  masterTaskTable: (params: object) => ["master-tasks", "table", params] as const,
  masterTaskTableRoot: ["master-tasks", "table"] as const,
  trackingTasks: (params: object) => ["tasks", "tracking", params] as const,
  trackingTasksRoot: ["tasks", "tracking"] as const,
  trackingPendingItems: (params: object) => ["pending-items", "tracking", params] as const,
  trackingPendingItemsRoot: ["pending-items", "tracking"] as const,
  trackingProjects: (params: object) => ["projects", "tracking", params] as const,
  trackingProjectsRoot: ["projects", "tracking"] as const,
  trackingProjectDetail: (id: string) => ["projects", "tracking", "detail", id] as const,
  taskReports: (params: object) => ["reports", "tasks", params] as const,
  taskReportsRoot: ["reports", "tasks"] as const,
  pendingItemReports: (params: object) => ["reports", "pending-items", params] as const,
  pendingItemReportsRoot: ["reports", "pending-items"] as const,
  projectReports: (params: object) => ["reports", "projects", params] as const,
  projectReportsRoot: ["reports", "projects"] as const,
  timezones: ["timezones"] as const,
  workspaces: ["workspaces"] as const,
  workspaceManagement: ["workspaces", "management"] as const,
  workspaceMembers: (workspaceId: string) => ["workspaces", workspaceId, "members"] as const,
  workspaceInvitations: (workspaceId: string) => ["workspaces", workspaceId, "invitations"] as const,
  myWorkspaceInvitations: ["workspace-invitations", "mine"] as const,
  userSettings: ["user-settings"] as const,
  dashboardSummary: (workspaceId: string) => ["dashboard", "summary", workspaceId] as const,
  dashboardStatistics: (workspaceId: string) => ["dashboard", "statistics", workspaceId] as const,
  reportTaskCounts: (workspaceId: string, scheduledFrom: string, scheduledTo: string) =>
    ["reports", "task-counts", workspaceId, scheduledFrom, scheduledTo] as const,
  categories: (workspaceId: string, active: boolean | null) =>
    ["categories", workspaceId, active] as const,
  categoriesForWorkspace: (workspaceId: string) => ["categories", workspaceId] as const,
  projects: (workspaceId: string, active: boolean | null) =>
    ["projects", workspaceId, active] as const,
  projectsForWorkspace: (workspaceId: string) => ["projects", workspaceId] as const,
  tasks: (workspaceId: string, filters: object) => ["tasks", workspaceId, filters] as const,
  tasksForWorkspace: (workspaceId: string) => ["tasks", workspaceId] as const,
  taskSeries: (workspaceId: string, active: boolean | null) => ["task-series", workspaceId, active] as const,
  taskSeriesForWorkspace: (workspaceId: string) => ["task-series", workspaceId] as const,
  workspaceSettings: (workspaceId: string) => ["workspace-settings", workspaceId] as const,
  dailyWorkflow: (workspaceId: string, date: string) => ["daily-workflow", workspaceId, date] as const,
  dailyFormDefinition: (workspaceId: string) => ["daily-form", "definition", workspaceId] as const,
  dailyFormSubmission: (workspaceId: string, date: string) => ["daily-form", "submission", workspaceId, date] as const
};
