import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useMemo, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { queryKeys } from "../../api/queryKeys";
import { deleteV2Activity, leaveV2Activity } from "../../api/v2ActivityApi";
import { getMyCalendar } from "../../api/v2CalendarApi";
import { useAuth } from "../../hooks/useAuth";
import { useWorkspaces } from "../../hooks/useWorkspaces";
import type { CalendarActivity, CalendarUntimed } from "../../types/v2Calendar";
import { activityLocalDate, addCalendarDays, addCalendarMonths, calendarRange, localCalendarDate, type CalendarView } from "../../utils/calendarRange";

const dateLabel = (value: string, zone: string, weekday = false) => new Intl.DateTimeFormat("es-PE", { timeZone: zone, day: "2-digit", month: "short", year: "numeric", ...(weekday ? { weekday: "short" as const } : {}) }).format(new Date(`${value}T12:00:00Z`));
const timeLabel = (value: string, zone: string) => new Intl.DateTimeFormat("es-PE", { timeZone: zone, hour: "2-digit", minute: "2-digit" }).format(new Date(value));
const countLabel = (value: number, singular: string, plural: string) => `${value} ${value === 1 ? singular : plural}`;

function UntimedGroup({ title, items, day }: { title: string; items: CalendarUntimed[]; day: string }) {
  const matching = items.filter((item) => item.planned_date === day);
  return matching.length ? <div className="calendar-untimed"><h3>{title}</h3>{matching.map((item) => <div key={item.id}><span>{item.name}</span><small>{item.workspace.name}</small></div>)}</div> : null;
}

export function MyCalendarPage() {
  const { user } = useAuth(); const workspaces = useWorkspaces(); const client = useQueryClient();
  const [searchParams] = useSearchParams();
  const requestedDate = /^\d{4}-\d{2}-\d{2}$/.test(searchParams.get("date") ?? "") ? searchParams.get("date")! : null;
  const requestedActivityId = searchParams.get("activity");
  const [view, setView] = useState<CalendarView>(() => requestedDate || window.matchMedia("(max-width: 48rem)").matches ? "DAY" : "WEEK");
  const [anchor, setAnchor] = useState(() => requestedDate ?? (user ? localCalendarDate(new Date(), user.timezone) : ""));
  const [workspaceId, setWorkspaceId] = useState(""); const [selected, setSelected] = useState<CalendarActivity | null>(null); const [feedback, setFeedback] = useState<string | null>(null);
  const range = useMemo(() => user && anchor ? calendarRange(anchor, view, user.timezone) : null, [anchor, user, view]);
  const projection = view === "MONTH" ? "MONTH" : "DETAIL";
  const calendar = useQuery({ queryKey: queryKeys.myCalendar(user?.id ?? "anonymous", range?.from ?? "", range?.to ?? "", projection, workspaceId || "ALL"), queryFn: () => getMyCalendar(range!.from, range!.to, projection, workspaceId || undefined), enabled: Boolean(user && range) });
  // Deep-link selection must wait for the asynchronously loaded calendar result.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { if (requestedActivityId && calendar.data) setSelected(calendar.data.items.find((item) => item.activity_id === requestedActivityId) ?? null); }, [calendar.data, requestedActivityId]);
  const refresh = async (item: CalendarActivity) => Promise.all([client.invalidateQueries({ queryKey: queryKeys.myCalendarRoot(user!.id) }), client.invalidateQueries({ queryKey: queryKeys.v2ActivitiesRoot(item.workspace.id) })]);
  const mutation = useMutation({ mutationFn: (operation: () => Promise<unknown>) => operation(), onSuccess: async () => { const item = selected!; setSelected(null); setFeedback("Calendario actualizado."); await refresh(item); }, onError: async () => { const item = selected; setFeedback("No pudimos actualizar la Actividad."); if (item) await refresh(item); } });
  if (!user || !range) return <section><h1>Mi calendario</h1><p>Cargando calendario…</p></section>;
  const dayCount = Math.round((new Date(`${range.after}T12:00:00Z`).getTime() - new Date(`${range.first}T12:00:00Z`).getTime()) / 86400000);
  const days = Array.from({ length: dayCount }, (_, index) => addCalendarDays(range.first, index));
  const move = (direction: number) => setAnchor(view === "MONTH" ? addCalendarMonths(anchor, direction) : addCalendarDays(anchor, direction * (view === "WEEK" ? 7 : 1)));
  return <section className="my-calendar-page"><header><p className="eyebrow">Calendario personal</p><h1>{workspaceId ? "Calendario del Workspace" : "Mi calendario"}</h1><Link className="primary-button" to="/calendario/comparar">Comparar</Link></header>
    <label className="calendar-workspace-context">Contexto<select aria-label="Contexto de calendario" value={workspaceId} onChange={(event) => setWorkspaceId(event.target.value)}><option value="">Todos mis Workspaces</option>{workspaces.data?.filter((item) => item.lifecycle === "ACTIVE").map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
    <div className="calendar-toolbar" aria-label="Navegación del calendario"><div><button type="button" aria-label="Periodo anterior" onClick={() => move(-1)}>‹</button><button type="button" onClick={() => setAnchor(localCalendarDate(new Date(), user.timezone))}>Hoy</button><button type="button" aria-label="Periodo siguiente" onClick={() => move(1)}>›</button></div><strong>{view === "WEEK" ? `${dateLabel(range.first, user.timezone)} – ${dateLabel(addCalendarDays(range.after, -1), user.timezone)}` : view === "MONTH" ? new Intl.DateTimeFormat("es-PE", { month: "long", year: "numeric", timeZone: user.timezone }).format(new Date(`${range.first}T12:00:00Z`)) : dateLabel(range.first, user.timezone, true)}</strong><div role="group" aria-label="Vista del calendario"><button type="button" aria-pressed={view === "DAY"} onClick={() => setView("DAY")}>Día</button><button type="button" aria-pressed={view === "WEEK"} onClick={() => setView("WEEK")}>Semana</button><button type="button" aria-pressed={view === "MONTH"} onClick={() => setView("MONTH")}>Mes</button></div></div>
    {feedback ? <p role="status">{feedback}</p> : null}
    {calendar.isPending ? <p role="status">Cargando calendario…</p> : calendar.isError ? <div role="alert"><p>No pudimos cargar el calendario.</p><button type="button" onClick={() => void calendar.refetch()}>Reintentar</button></div> : view === "MONTH" ? <div className="calendar-month" aria-label="Vista mensual">{days.map((day) => { const counts = calendar.data.daily_counts?.find((item) => item.date === day); return <button type="button" className="calendar-month__day" key={day} onClick={() => { setAnchor(day); setView("DAY"); }}><strong>{Number(day.slice(-2))}</strong>{counts?.activities ? <span>{countLabel(counts.activities, "actividad", "actividades")}</span> : null}{counts?.tasks ? <span>{countLabel(counts.tasks, "tarea", "tareas")}</span> : null}{counts?.pending_items ? <span>{countLabel(counts.pending_items, "pendiente", "pendientes")}</span> : null}{counts?.project_stages ? <span>{countLabel(counts.project_stages, "etapa", "etapas")}</span> : null}</button>; })}</div> : calendar.data.items.length + (calendar.data.tasks?.length ?? 0) + (calendar.data.pending_items?.length ?? 0) + (calendar.data.project_stages?.length ?? 0) === 0 ? <p className="review-empty">No hay elementos en este periodo.</p> : <div className={view === "WEEK" ? "calendar-grid calendar-grid--week" : "calendar-grid calendar-grid--day"}>{days.map((day) => <section className="calendar-day" key={day} aria-label={dateLabel(day, user.timezone, true)}><h2>{dateLabel(day, user.timezone, true)}</h2><div className="calendar-day__activities">{calendar.data.items.filter((item) => activityLocalDate(item.starts_at, user.timezone) === day).map((item) => <button type="button" className={`calendar-activity calendar-activity--color-${item.workspace.color.toLowerCase()}`} key={item.activity_id} onClick={() => setSelected(item)}><strong>{item.activity_name}</strong><span>{timeLabel(item.starts_at, user.timezone)}–{timeLabel(item.ends_at, user.timezone)}</span><small>{item.workspace.name}</small></button>)}</div><UntimedGroup title="Tareas" items={calendar.data.tasks ?? []} day={day} /><UntimedGroup title="Pendientes" items={calendar.data.pending_items ?? []} day={day} /><UntimedGroup title="Etapas" items={calendar.data.project_stages ?? []} day={day} /></section>)}</div>}
    {selected ? <dialog open className="calendar-detail"><h2>{selected.activity_name}</h2><p>{dateLabel(activityLocalDate(selected.starts_at, user.timezone), user.timezone, true)}</p><p>{timeLabel(selected.starts_at, user.timezone)}–{timeLabel(selected.ends_at, user.timezone)}</p><p><strong>Workspace:</strong> {selected.workspace.name}</p><p><strong>Categoría:</strong> {selected.category_name}</p><p><strong>Organizador:</strong> {selected.organizer.display_name}</p><p><strong>Participantes:</strong> {selected.participants.map((item) => item.display_name).join(", ") || "Sin participantes"}</p><p>{selected.temporal_state === "FUTURE" ? "Próxima" : selected.temporal_state === "IN_PROGRESS" ? "En curso" : "Finalizada"}</p><div>{selected.can_delete ? <button type="button" disabled={mutation.isPending} onClick={() => mutation.mutate(() => deleteV2Activity(selected.workspace.id, selected.activity_id, selected.lock_version))}>Eliminar</button> : null}{selected.can_leave_participation ? <button type="button" disabled={mutation.isPending} onClick={() => mutation.mutate(() => leaveV2Activity(selected.workspace.id, selected.activity_id, selected.lock_version))}>Retirarme</button> : null}<button type="button" onClick={() => setSelected(null)}>Cerrar</button></div></dialog> : null}
  </section>;
}
