import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { MemoryRouter } from "react-router-dom";
import { beforeEach, describe, expect, it, vi } from "vitest";
import * as api from "../../api/v2ProjectApi";
import * as workspaceApi from "../../api/workspaceApi";
import { PlanningProjectsPage } from "./PlanningProjectsPage";

vi.mock("../../api/v2ProjectApi", () => ({ listV2Projects: vi.fn(), getV2Project: vi.fn(), createV2Project: vi.fn(), updateV2Project: vi.fn(), deactivateV2Project: vi.fn(), reactivateV2Project: vi.fn() }));
vi.mock("../../api/workspaceApi", () => ({ listWorkspaceMembers: vi.fn() }));
vi.mock("../../components/common/V2CatalogSelector", () => ({ CategorySelector: ({ value, onChange }: { value: string; onChange: (value: string) => void }) => <label>Categoría<select value={value} onChange={(event) => onChange(event.target.value)}><option value="">Selecciona</option><option value="category-1">Casa</option></select></label> }));
const auth = { user: { id: "user-1", email: "ana@example.com", first_name: "Ana", last_name: "Uno", timezone: "America/Lima" }, workspace: { id: "workspace-a", name: "Familia", kind: "SHARED" as "SHARED" | "PERSONAL", timezone: "America/Lima" } };
vi.mock("../../hooks/useAuth", () => ({ useAuth: () => auth }));
const project = { id: "project-1", workspace_id: "workspace-a", category_id: "category-1", category_name: "Casa", leader_user_id: "user-2", leader_display_name: "Luis Dos", leader_email: "luis@example.com", name: "Mudanza", description: "Preparar casa", is_active: true, planned_date: null, progress: 0, state: "NO_INICIADO", compliance: null, compliance_detail_days: null, completion_date: null, weights_complete: false, stage_count: 0, total_weight: "0", lock_version: 3, can_edit: true, can_deactivate: true, can_reactivate: false, created_at: "", updated_at: "" };
function mount() { const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); const view = () => <MemoryRouter><QueryClientProvider client={client}><PlanningProjectsPage /></QueryClientProvider></MemoryRouter>; return { ...render(view()), view }; }
describe("V2 PlanningProjectsPage", () => {
  beforeEach(() => { auth.workspace = { id: "workspace-a", name: "Familia", kind: "SHARED", timezone: "America/Lima" }; vi.clearAllMocks(); vi.mocked(workspaceApi.listWorkspaceMembers).mockResolvedValue([{ user_id: "user-1", display_name: "Ana Uno", email: "ana@example.com", role: "Miembro", status: "ACTIVE", joined_at: "", ended_at: null }, { user_id: "user-2", display_name: "Luis Dos", email: "luis@example.com", role: "Miembro", status: "ACTIVE", joined_at: "", ended_at: null }]); const list = { items: [project], total: 1, page: 1, page_size: 25, total_pages: 1 }; vi.mocked(api.listV2Projects).mockResolvedValue(list); vi.mocked(api.getV2Project).mockResolvedValue(project); vi.mocked(api.createV2Project).mockResolvedValue(project); vi.mocked(api.updateV2Project).mockResolvedValue(project); vi.mocked(api.deactivateV2Project).mockResolvedValue({ ...project, is_active: false }); vi.mocked(api.reactivateV2Project).mockResolvedValue(project); });
  it("creates a Shared Project with Category and active leader", async () => { const user = userEvent.setup(); mount(); const form = screen.getByRole("heading", { name: "Crear Proyecto" }).closest("section")!; await user.selectOptions(within(form).getByLabelText("Categoría"), "category-1"); await user.type(within(form).getByLabelText("Nombre"), "Viaje"); await user.selectOptions(await within(form).findByLabelText("Líder"), "user-2"); await user.click(within(form).getByRole("button", { name: "Crear" })); await waitFor(() => expect(api.createV2Project).toHaveBeenCalledWith("workspace-a", { category_id: "category-1", leader_user_id: "user-2", name: "Viaje", description: null })); });
  it("derives the Personal leader server-side", async () => { auth.workspace = { id: "personal-a", name: "Personal", kind: "PERSONAL", timezone: "America/Lima" }; const user = userEvent.setup(); mount(); const form = screen.getByRole("heading", { name: "Crear Proyecto" }).closest("section")!; expect(within(form).getByText("Líder: tú")).toBeInTheDocument(); await user.selectOptions(within(form).getByLabelText("Categoría"), "category-1"); await user.type(within(form).getByLabelText("Nombre"), "Viaje"); await user.click(within(form).getByRole("button", { name: "Crear" })); await waitFor(() => expect(api.createV2Project).toHaveBeenCalledWith("personal-a", { category_id: "category-1", name: "Viaje", description: null })); });
  it("lists zero-stage derived data and links to hierarchical detail", async () => { mount(); expect(await screen.findByText("Mudanza")).toBeInTheDocument(); expect(screen.getByText("Avance: 0%")).toBeInTheDocument(); expect(screen.getByRole("link", { name: "Abrir Proyecto Mudanza" })).toHaveAttribute("href", "/planificacion/proyectos/project-1"); });
  it("uses lock_version for lifecycle and exposes no delete", async () => { const user = userEvent.setup(); mount(); await user.click(await screen.findByRole("button", { name: "Desactivar" })); await waitFor(() => expect(api.deactivateV2Project).toHaveBeenCalledWith("workspace-a", "project-1", 3)); expect(screen.queryByRole("button", { name: /eliminar/i })).not.toBeInTheDocument(); });
  it("resets filters when Workspace changes", async () => { const user = userEvent.setup(); const mounted = mount(); await screen.findByText("Mudanza"); await user.type(screen.getByLabelText("Buscar"), "privado"); await waitFor(() => expect(api.listV2Projects).toHaveBeenLastCalledWith("workspace-a", expect.objectContaining({ search: "privado" }))); auth.workspace = { id: "workspace-b", name: "Otro", kind: "SHARED", timezone: "America/Lima" }; mounted.rerender(mounted.view()); await waitFor(() => expect(api.listV2Projects).toHaveBeenLastCalledWith("workspace-b", { page: 1, page_size: 25 })); expect(screen.getByLabelText("Buscar")).toHaveValue(""); });
});
