import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, describe, expect, it, vi } from "vitest";
import * as api from "../../api/planningProjectApi";
import * as categoryApi from "../../api/planningPendingItemApi";
import type { PlanningProjectDetail } from "../../types/planningProject";
import { PlanningProjectsPage } from "./PlanningProjectsPage";
vi.mock("../../api/planningProjectApi", () => ({ listPlanningProjects: vi.fn(), getPlanningProject: vi.fn(), createPlanningProject: vi.fn(), updatePlanningProject: vi.fn(), createPlanningProjectStep: vi.fn(), updatePlanningProjectStep: vi.fn() }));
vi.mock("../../api/planningPendingItemApi", () => ({ listAllCategoryOptions: vi.fn() }));
const categories = [{ id: "category-1", name: "Personal", created_at: "", updated_at: "" }];
const detail: PlanningProjectDetail = { id: "project-1", category_id: "category-1", category: { id: "category-1", name: "Personal" }, name: "Mudanza", is_active: false, planned_date: "2026-09-02", progress: null, state: null, total_weight: "100.00", general_comment: "privado", last_tracking_saved_at: null, lock_version: 4, created_at: "", updated_at: "", steps: [
  { id: "step-2", name: "Transportar", planned_date: "2026-09-02", weight: "60.00", progress: 30, state: "EN_PROCESO", completion_date: null, compliance: null, detail_days: null, comment: "privado", position: 2, lock_version: 8, created_at: "", updated_at: "" },
  { id: "step-1", name: "Empacar", planned_date: "2026-09-01", weight: "40.00", progress: 0, state: "NO_INICIADO", completion_date: null, compliance: null, detail_days: null, comment: null, position: 1, lock_version: 7, created_at: "", updated_at: "" }
] };
const list = { items: [detail], total: 26, page: 1, page_size: 25, total_pages: 2 };
function renderPage() { const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); render(<QueryClientProvider client={client}><PlanningProjectsPage /></QueryClientProvider>); return client; }
describe("PlanningProjectsPage", () => {
  beforeEach(() => { vi.clearAllMocks(); vi.mocked(categoryApi.listAllCategoryOptions).mockResolvedValue(categories); vi.mocked(api.listPlanningProjects).mockResolvedValue(list); vi.mocked(api.getPlanningProject).mockResolvedValue(detail); vi.mocked(api.createPlanningProject).mockResolvedValue(detail); vi.mocked(api.updatePlanningProject).mockResolvedValue(detail); vi.mocked(api.createPlanningProjectStep).mockResolvedValue(detail.steps[0]); vi.mocked(api.updatePlanningProjectStep).mockResolvedValue(detail.steps[0]); });
  it("renders the register and server filters with pagination", async () => { const user = userEvent.setup(); renderPage(); const register = await screen.findByRole("table", { name: "Registro de Proyectos" }); expect(within(register).getByText("Mudanza")).toBeInTheDocument(); expect(within(register).getByRole("button", { name: "Ver estructura de Mudanza" })).toHaveTextContent("›"); expect(within(register).queryByText("Ver estructura")).not.toBeInTheDocument(); const section = screen.getByRole("heading", { name: "Registro de Proyectos" }).closest<HTMLElement>("section")!; await user.selectOptions(within(section).getByLabelText("Vigencia"), "false"); await user.selectOptions(within(section).getByLabelText("Por página"), "50"); await waitFor(() => expect(api.listPlanningProjects).toHaveBeenCalledWith(expect.objectContaining({ page: 1, page_size: 50, is_active: false }))); expect(within(section).getByLabelText("Por página")).toHaveTextContent("2550100"); });
  it("creates an inactive empty Project using Category options", async () => { const user = userEvent.setup(); renderPage(); await screen.findByText("Mudanza"); const section = screen.getByRole("heading", { name: "Crear Proyecto" }).closest<HTMLElement>("section")!; await user.selectOptions(within(section).getByLabelText("Categoría"), "category-1"); await user.type(within(section).getByLabelText("Nombre"), "Viaje"); await user.click(within(section).getByRole("button", { name: "Crear" })); await waitFor(() => expect(api.createPlanningProject).toHaveBeenCalledWith({ category_id: "category-1", name: "Viaje", is_active: false, steps: [] })); });
  it("validates active structure with exact decimal total and never normalizes weights", async () => { const user = userEvent.setup(); renderPage(); await screen.findByText("Mudanza"); const section = screen.getByRole("heading", { name: "Crear Proyecto" }).closest<HTMLElement>("section")!; await user.selectOptions(within(section).getByLabelText("Categoría"), "category-1"); await user.type(within(section).getByLabelText("Nombre"), "Viaje"); await user.selectOptions(within(section).getByLabelText("Vigencia"), "active"); await user.type(within(section).getByLabelText("Nombre del Paso 1"), "Comprar pasajes"); await user.type(within(section).getByLabelText("Fecha del Paso 1"), "2026-09-01"); await user.type(within(section).getByLabelText("Peso del Paso 1"), "99.99"); await user.click(within(section).getByRole("button", { name: "Crear" })); expect(await screen.findByRole("alert")).toHaveTextContent("exactamente 100.00"); expect(api.createPlanningProject).not.toHaveBeenCalled(); expect(within(section).getByLabelText("Peso del Paso 1")).toHaveValue("99.99"); });
  it("shows Steps in position order and permits structure editing only while inactive", async () => { const user = userEvent.setup(); renderPage(); await user.click(await screen.findByRole("button", { name: "Ver estructura de Mudanza" })); const steps = await screen.findByRole("table", { name: "Pasos del Proyecto" }); expect(within(steps).getAllByRole("row")[1]).toHaveTextContent("Empacar"); expect(within(steps).getAllByRole("row")[2]).toHaveTextContent("Transportar"); expect(screen.getByRole("button", { name: "Editar Paso Empacar" })).toBeEnabled(); expect(screen.getByRole("heading", { name: "Agregar Paso" })).toBeInTheDocument(); expect(screen.queryByText("privado")).not.toBeInTheDocument(); expect(screen.queryByText("30")).not.toBeInTheDocument(); });
  it("creates and edits Step planning fields with Step lock_version", async () => { const user = userEvent.setup(); renderPage(); await user.click(await screen.findByRole("button", { name: "Ver estructura de Mudanza" })); await screen.findByRole("table", { name: "Pasos del Proyecto" }); await user.type(screen.getByLabelText("Nombre del nuevo Paso"), "Limpiar"); await user.type(screen.getByLabelText("Fecha del nuevo Paso"), "2026-09-03"); await user.type(screen.getByLabelText("Peso del nuevo Paso"), "10.00"); const newStepForm = screen.getByRole("heading", { name: "Agregar Paso" }).closest<HTMLElement>("form")!; await user.click(within(newStepForm).getByRole("button", { name: "Agregar Paso" })); await waitFor(() => expect(api.createPlanningProjectStep).toHaveBeenCalledWith("project-1", expect.objectContaining({ name: "Limpiar", weight: "10.00" }))); await user.click(screen.getByRole("button", { name: "Editar Paso Empacar" })); fireEvent.submit(screen.getByRole("button", { name: "Guardar Paso" }).closest("form")!); await waitFor(() => expect(api.updatePlanningProjectStep).toHaveBeenCalledWith("project-1", "step-1", expect.objectContaining({ lock_version: 7, position: 1, name: "Empacar" }))); });
  it("disables active structural controls", async () => { vi.mocked(api.getPlanningProject).mockResolvedValue({ ...detail, is_active: true }); const user = userEvent.setup(); renderPage(); await user.click(await screen.findByRole("button", { name: "Ver estructura de Mudanza" })); expect(await screen.findByRole("button", { name: "Editar Paso Empacar" })).toBeDisabled(); expect(screen.queryByRole("heading", { name: "Agregar Paso" })).not.toBeInTheDocument(); });
  it("uses Project lock_version and clears stale editing after 409", async () => { vi.mocked(api.updatePlanningProject).mockRejectedValue({ isAxiosError: true, response: { status: 409 } }); const user = userEvent.setup(); renderPage(); await user.click(await screen.findByRole("button", { name: "Ver estructura de Mudanza" })); await user.click(await screen.findByRole("button", { name: "Editar Proyecto" })); await user.click(screen.getByRole("button", { name: "Guardar Proyecto" })); await waitFor(() => expect(api.updatePlanningProject).toHaveBeenCalledWith("project-1", expect.objectContaining({ lock_version: 4 }))); expect(await screen.findByRole("alert")).toHaveTextContent("cambió desde la última carga"); await waitFor(() => expect(screen.queryByLabelText("Nombre del Proyecto")).not.toBeInTheDocument()); });
  it("clears stale Step editing after a 409", async () => { vi.mocked(api.updatePlanningProjectStep).mockRejectedValue({ isAxiosError: true, response: { status: 409 } }); const user = userEvent.setup(); renderPage(); await user.click(await screen.findByRole("button", { name: "Ver estructura de Mudanza" })); await user.click(await screen.findByRole("button", { name: "Editar Paso Empacar" })); fireEvent.submit(screen.getByRole("button", { name: "Guardar Paso" }).closest("form")!); await waitFor(() => expect(api.updatePlanningProjectStep).toHaveBeenCalledWith("project-1", "step-1", expect.objectContaining({ lock_version: 7 }))); expect(await screen.findByRole("alert")).toHaveTextContent("cambió desde la última carga"); await waitFor(() => expect(screen.queryByLabelText("Nombre de Empacar")).not.toBeInTheDocument()); });
  it("activates only a complete 100.00 structure", async () => { const user = userEvent.setup(); renderPage(); await user.click(await screen.findByRole("button", { name: "Ver estructura de Mudanza" })); await user.click(await screen.findByRole("button", { name: "Editar Proyecto" })); await user.selectOptions(screen.getByLabelText("Vigencia del Proyecto"), "active"); await user.click(screen.getByRole("button", { name: "Guardar Proyecto" })); await waitFor(() => expect(api.updatePlanningProject).toHaveBeenCalledWith("project-1", { category_id: "category-1", name: "Mudanza", is_active: true, lock_version: 4 })); });
  it("shows a safe Project-list error and retries", async () => { vi.mocked(api.listPlanningProjects).mockRejectedValueOnce(new Error("network")).mockResolvedValueOnce(list); const user = userEvent.setup(); renderPage(); expect(await screen.findByRole("alert")).toHaveTextContent("No pudimos cargar los Proyectos"); await user.click(screen.getByRole("button", { name: "Reintentar" })); expect(await screen.findByText("Mudanza")).toBeInTheDocument(); });
  it("has no deletion or Tracking editing and handles no Categories", async () => { vi.mocked(categoryApi.listAllCategoryOptions).mockResolvedValue([]); renderPage(); expect(await screen.findByText("Aún no hay Categorías configuradas en Tablas > Categorías.")).toBeInTheDocument(); expect(screen.queryByRole("button", { name: /eliminar/i })).not.toBeInTheDocument(); expect(screen.queryByLabelText(/progreso|comentario/i)).not.toBeInTheDocument(); });
});
