import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, describe, expect, it, vi } from "vitest";
import * as api from "../../api/v2PendingItemApi";
import * as workspaceApi from "../../api/workspaceApi";
import { PlanningPendingItemsPage } from "./PlanningPendingItemsPage";

vi.mock("../../api/v2PendingItemApi", () => ({ listV2PendingItems: vi.fn(), createV2PendingItem: vi.fn(), updateV2PendingItem: vi.fn(), updateV2PendingItemProgress: vi.fn(), correctV2PendingItem: vi.fn(), deactivateV2PendingItem: vi.fn(), reactivateV2PendingItem: vi.fn(), deleteV2PendingItem: vi.fn() }));
vi.mock("../../api/workspaceApi", () => ({ listWorkspaceMembers: vi.fn() }));
vi.mock("../../components/common/V2CatalogSelector", () => ({ CategorySelector: ({ value, onChange }: { value: string; onChange: (value: string) => void }) => <label>Categoría<select aria-label="Categoría" value={value} onChange={(event) => onChange(event.target.value)}><option value="">Selecciona</option><option value="category-1">Casa</option></select></label> }));

const auth = { user: { id: "user-1", email: "ana@example.com", first_name: "Ana", last_name: "Uno", timezone: "America/Lima" }, workspace: { id: "workspace-a", name: "Familia", kind: "SHARED" as "SHARED" | "PERSONAL", timezone: "America/Lima" } };
vi.mock("../../hooks/useAuth", () => ({ useAuth: () => auth }));
const item = { id: "pending-1", workspace_id: "workspace-a", category_id: "category-1", category_name: "Casa", responsible_user_id: "user-1", responsible_display_name: "Ana Uno", responsible_email: "ana@example.com", name: "Renovar documento", is_active: true, planned_date: "2026-08-20", progress: 20, state: "EN_PROCESO" as const, completion_date: null, compliance: "ATRASADO" as const, compliance_detail_days: 6, lock_version: 7, can_edit: true, can_update_progress: true, can_correct: false, can_deactivate: true, can_reactivate: false, can_delete: false, created_at: "", updated_at: "" };

function renderPage() { const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); return { ...render(<QueryClientProvider client={client}><PlanningPendingItemsPage /></QueryClientProvider>), client }; }

describe("V2 PlanningPendingItemsPage", () => {
  beforeEach(() => { auth.workspace = { id: "workspace-a", name: "Familia", kind: "SHARED", timezone: "America/Lima" }; vi.clearAllMocks(); vi.mocked(workspaceApi.listWorkspaceMembers).mockResolvedValue([{ user_id: "user-1", display_name: "Ana Uno", email: "ana@example.com", role: "Miembro", status: "ACTIVE", joined_at: "", ended_at: null }]); vi.mocked(api.listV2PendingItems).mockResolvedValue({ items: [item], total: 1, page: 1, page_size: 25, total_pages: 1 }); vi.mocked(api.createV2PendingItem).mockResolvedValue(item); vi.mocked(api.updateV2PendingItem).mockResolvedValue(item); vi.mocked(api.updateV2PendingItemProgress).mockResolvedValue(item); vi.mocked(api.correctV2PendingItem).mockResolvedValue(item); vi.mocked(api.deactivateV2PendingItem).mockResolvedValue(item); vi.mocked(api.reactivateV2PendingItem).mockResolvedValue(item); vi.mocked(api.deleteV2PendingItem).mockResolvedValue(); });

  it("creates in the active Shared Workspace with an explicit responsible member", async () => { const user = userEvent.setup(); renderPage(); const form = screen.getByRole("heading", { name: "Crear Pendiente" }).closest("section")!; await user.selectOptions(within(form).getByLabelText("Categoría"), "category-1"); await user.type(within(form).getByLabelText("Nombre"), "Comprar lentes"); await user.selectOptions(await within(form).findByLabelText("Responsable"), "user-1"); await user.type(within(form).getByLabelText("Fecha planificada"), "2026-08-30"); await user.click(within(form).getByRole("button", { name: "Crear" })); await waitFor(() => expect(api.createV2PendingItem).toHaveBeenCalledWith("workspace-a", { category_id: "category-1", responsible_user_id: "user-1", name: "Comprar lentes", planned_date: "2026-08-30" })); });

  it("derives the responsible user for Personal Workspace", async () => { auth.workspace = { id: "personal-a", name: "Personal", kind: "PERSONAL", timezone: "America/Lima" }; const user = userEvent.setup(); renderPage(); const form = screen.getByRole("heading", { name: "Crear Pendiente" }).closest("section")!; expect(within(form).queryByLabelText("Responsable")).not.toBeInTheDocument(); await user.selectOptions(within(form).getByLabelText("Categoría"), "category-1"); await user.type(within(form).getByLabelText("Nombre"), "Comprar lentes"); await user.type(within(form).getByLabelText("Fecha planificada"), "2026-08-30"); await user.click(within(form).getByRole("button", { name: "Crear" })); await waitFor(() => expect(api.createV2PendingItem).toHaveBeenCalledWith("personal-a", { category_id: "category-1", name: "Comprar lentes", planned_date: "2026-08-30" })); });

  it("shows progress, derived state and compliance detail", async () => { renderPage(); expect(await screen.findByText("20% · EN_PROCESO")).toBeInTheDocument(); expect(screen.getByText("ATRASADO · 6 día(s)")).toBeInTheDocument(); });

  it("uses the explicit correction flow for finalized records", async () => { vi.mocked(api.listV2PendingItems).mockResolvedValue({ items: [{ ...item, progress: 100, state: "FINALIZADO", can_edit: false, can_update_progress: false, can_correct: true, can_deactivate: false }], total: 1, page: 1, page_size: 25, total_pages: 1 }); const user = userEvent.setup(); renderPage(); expect(await screen.findByRole("button", { name: "Corregir Renovar documento" })).toBeInTheDocument(); expect(screen.queryByRole("button", { name: "Editar" })).not.toBeInTheDocument(); await user.click(screen.getByRole("button", { name: "Corregir Renovar documento" })); expect(screen.getByText("La corrección reabre el Pendiente y conserva el historial.")).toBeInTheDocument(); await user.clear(screen.getByLabelText("Avance")); await user.type(screen.getByLabelText("Avance"), "80"); await user.click(screen.getByRole("button", { name: "Guardar" })); await waitFor(() => expect(api.correctV2PendingItem).toHaveBeenCalledWith("workspace-a", "pending-1", 80, 7)); });

  it("offers hard deletion only when projected by the server", async () => { vi.mocked(api.listV2PendingItems).mockResolvedValue({ items: [{ ...item, progress: 0, state: "NO_INICIADO", can_delete: true }], total: 1, page: 1, page_size: 25, total_pages: 1 }); vi.spyOn(window, "confirm").mockReturnValue(true); const user = userEvent.setup(); renderPage(); await user.click(await screen.findByRole("button", { name: "Eliminar" })); await waitFor(() => expect(api.deleteV2PendingItem).toHaveBeenCalledWith("workspace-a", "pending-1", 7)); });

  it("discards stale dialog state and refreshes after a conflict", async () => { vi.mocked(api.updateV2PendingItem).mockRejectedValue({ isAxiosError: true, response: { status: 409 } }); const user = userEvent.setup(); renderPage(); await user.click(await screen.findByRole("button", { name: "Editar" })); await user.click(screen.getByRole("button", { name: "Guardar" })); expect(await screen.findByText(/cambió desde la última carga/)).toBeInTheDocument(); expect(screen.queryByRole("dialog")).not.toBeInTheDocument(); });
});
