import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, describe, expect, it, vi } from "vitest";
import * as api from "../../api/planningTaskApi";
import type { PlanningTask, PlanningTaskListResponse } from "../../types/planningTask";
import { PlanningTasksPage } from "./PlanningTasksPage";

vi.mock("../../api/planningTaskApi", () => ({ listAllMasterTasks: vi.fn(), listPlanningTasks: vi.fn(), createPlanningTask: vi.fn(), createPlanningTasksBulk: vi.fn(), updatePlanningTask: vi.fn(), deletePlanningTask: vi.fn(), deletePlanningTasksBulk: vi.fn() }));
const master = { id: "master-1", name: "Salir a correr", category_id: "category-1", category: { id: "category-1", name: "Actividad" }, created_at: "", updated_at: "" };
const makeTask = (id: string, status: PlanningTask["status"], name = "Salir a correr"): PlanningTask => ({ id, master_task_id: master.id, planned_date: "2026-08-20", status, result: null, resolved_at: null, resolved_by_id: null, master_task: { ...master, name }, lock_version: 2, created_at: "", updated_at: "" });
const list: PlanningTaskListResponse = { items: [makeTask("scheduled", "PROGRAMADA"), makeTask("pending", "PENDIENTE", "Leer"), makeTask("done", "COMPLETADA", "Ordenar"), makeTask("missed", "NO_REALIZADA", "Llamar")], total: 4, page: 1, page_size: 25, total_pages: 1 };
function renderPage() { const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); render(<QueryClientProvider client={client}><PlanningTasksPage /></QueryClientProvider>); return client; }

describe("PlanningTasksPage", () => {
  beforeEach(() => { vi.clearAllMocks(); vi.mocked(api.listAllMasterTasks).mockResolvedValue([master]); vi.mocked(api.listPlanningTasks).mockResolvedValue(list); vi.mocked(api.createPlanningTask).mockResolvedValue(list.items[0]); vi.mocked(api.createPlanningTasksBulk).mockResolvedValue({ created_count: 2, items: [] }); vi.mocked(api.updatePlanningTask).mockResolvedValue(list.items[0]); vi.mocked(api.deletePlanningTasksBulk).mockResolvedValue({ deleted_count: 1 }); vi.spyOn(window, "confirm").mockReturnValue(true); });
  it("renders target register fields, statuses and only scheduled mutation controls", async () => {
    renderPage(); expect(await screen.findByRole("option", { name: "Salir a correr — Actividad" })).toBeInTheDocument();
    const register = screen.getByRole("table", { name: "Registro de tareas planificadas" });
    for (const status of ["Programada", "Pendiente", "Completada", "No realizada"]) expect(within(register).getByText(status)).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Editar fecha de Salir a correr" })).toBeInTheDocument();
    expect(screen.queryByRole("button", { name: "Editar fecha de Leer" })).not.toBeInTheDocument();
    expect(screen.getByLabelText("Seleccionar Leer")).toBeDisabled();
  });
  it("creates a single occurrence with only MasterTask and date", async () => {
    const user = userEvent.setup(); renderPage(); const creation = (await screen.findByRole("heading", { name: "Crear tareas" })).closest<HTMLElement>("section")!; await within(creation).findByRole("option", { name: "Salir a correr — Actividad" });
    await user.selectOptions(within(creation).getByLabelText("Tarea"), master.id); await user.type(within(creation).getByLabelText("Fecha"), "2026-08-25"); await user.click(within(creation).getByRole("button", { name: "Crear" }));
    await waitFor(() => expect(api.createPlanningTask).toHaveBeenCalledWith({ master_task_id: master.id, planned_date: "2026-08-25" }));
  });
  it("creates finite weekly occurrences with Monday=0 and has no monthly/persistent-series UI", async () => {
    const user = userEvent.setup(); renderPage(); const creation = (await screen.findByRole("heading", { name: "Crear tareas" })).closest<HTMLElement>("section")!; await within(creation).findByRole("option", { name: "Salir a correr — Actividad" }); await user.selectOptions(within(creation).getByLabelText("Tarea"), master.id); await user.selectOptions(within(creation).getByLabelText("Tipo de creación"), "bulk"); await user.type(within(creation).getByLabelText("Fecha inicial"), "2026-08-17"); await user.type(within(creation).getByLabelText("Fecha final"), "2026-08-24"); await user.selectOptions(within(creation).getByLabelText("Patrón"), "WEEKLY"); await user.click(within(creation).getByLabelText("Lunes")); await user.click(within(creation).getByLabelText("Miércoles")); await user.click(within(creation).getByRole("button", { name: "Crear" }));
    await waitFor(() => expect(api.createPlanningTasksBulk).toHaveBeenCalledWith({ master_task_id: master.id, start_date: "2026-08-17", end_date: "2026-08-24", pattern: "WEEKLY", weekdays: [0, 2] }));
    expect(screen.queryByText(/Mensual|TaskSeries|serie persistente/i)).not.toBeInTheDocument();
  });
  it("edits planned date only with lock version", async () => { const user = userEvent.setup(); renderPage(); await user.click(await screen.findByRole("button", { name: "Editar fecha de Salir a correr" })); const date = screen.getByLabelText("Nueva fecha de Salir a correr"); await user.clear(date); await user.type(date, "2026-08-26"); await user.click(screen.getByRole("button", { name: "Guardar fecha de Salir a correr" })); await waitFor(() => expect(api.updatePlanningTask).toHaveBeenCalledWith("scheduled", { planned_date: "2026-08-26", lock_version: 2 })); });
  it("closes stale date editing after a failed update", async () => { vi.mocked(api.updatePlanningTask).mockRejectedValue({ isAxiosError: true, response: { status: 409 } }); const user = userEvent.setup(); renderPage(); await user.click(await screen.findByRole("button", { name: "Editar fecha de Salir a correr" })); await user.click(screen.getByRole("button", { name: "Guardar fecha de Salir a correr" })); expect(await screen.findByRole("alert")).toHaveTextContent("cambió desde la última carga"); await waitFor(() => expect(screen.queryByLabelText("Nueva fecha de Salir a correr")).not.toBeInTheDocument()); expect(screen.getByRole("button", { name: "Editar fecha de Salir a correr" })).toBeInTheDocument(); });
  it("bulk deletes only selected scheduled rows in one request", async () => { const user = userEvent.setup(); renderPage(); await user.click(await screen.findByLabelText("Seleccionar Salir a correr")); await user.click(screen.getByRole("button", { name: "Eliminar seleccionadas" })); await waitFor(() => expect(api.deletePlanningTasksBulk).toHaveBeenCalledWith([{ id: "scheduled", lock_version: 2 }])); expect(api.deletePlanningTask).not.toHaveBeenCalled(); });
  it("clears stale selected lock versions after failed bulk deletion", async () => { vi.mocked(api.deletePlanningTasksBulk).mockRejectedValue({ isAxiosError: true, response: { status: 409 } }); const user = userEvent.setup(); renderPage(); const checkbox = await screen.findByLabelText("Seleccionar Salir a correr"); await user.click(checkbox); expect(screen.getByText("1 seleccionadas")).toBeInTheDocument(); await user.click(screen.getByRole("button", { name: "Eliminar seleccionadas" })); expect(await screen.findByRole("alert")).toHaveTextContent("cambió desde la última carga"); await waitFor(() => expect(checkbox).not.toBeChecked()); expect(screen.getByText("0 seleccionadas")).toBeInTheDocument(); expect(screen.getByRole("button", { name: "Eliminar seleccionadas" })).toBeDisabled(); });
  it("clears selected lock versions after failed single deletion", async () => { vi.mocked(api.deletePlanningTask).mockRejectedValue({ isAxiosError: true, response: { status: 409 } }); const user = userEvent.setup(); renderPage(); const checkbox = await screen.findByLabelText("Seleccionar Salir a correr"); await user.click(checkbox); await user.click(screen.getByRole("button", { name: "Eliminar Salir a correr" })); expect(await screen.findByRole("alert")).toHaveTextContent("cambió desde la última carga"); await waitFor(() => expect(checkbox).not.toBeChecked()); expect(screen.getByText("0 seleccionadas")).toBeInTheDocument(); });
  it("uses server filters and pagination defaults", async () => { const user = userEvent.setup(); renderPage(); await screen.findByText("Programada"); expect(api.listPlanningTasks).toHaveBeenCalledWith({ page: 1, page_size: 25 }); await user.selectOptions(screen.getByLabelText("Estado"), "PENDIENTE"); await waitFor(() => expect(api.listPlanningTasks).toHaveBeenCalledWith(expect.objectContaining({ page: 1, page_size: 25, status: "PENDIENTE" }))); expect(screen.getByLabelText("Por página")).toHaveValue("25"); expect(within(screen.getByLabelText("Por página")).getAllByRole("option").map((x) => x.textContent)).toEqual(["25","50","100"]); });
  it("shows the neutral no-MasterTask state without free text fallback", async () => { vi.mocked(api.listAllMasterTasks).mockResolvedValue([]); renderPage(); expect(await screen.findByText("Aún no hay tareas configuradas en Tablas > Tareas.")).toBeInTheDocument(); expect(screen.queryByLabelText("Nombre de tarea")).not.toBeInTheDocument(); });
});
