import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, describe, expect, it, vi } from "vitest";

import * as taskApi from "../../api/v2TaskApi";
import * as workspaceApi from "../../api/workspaceApi";
import { PlanningTasksPage } from "./PlanningTasksPage";

vi.mock("../../api/v2TaskApi", () => ({ listV2Tasks: vi.fn(), createV2Task: vi.fn(), createV2RecurringTasks: vi.fn(), updateV2Task: vi.fn(), resolveV2Task: vi.fn(), deleteV2Task: vi.fn() }));
vi.mock("../../api/workspaceApi", () => ({ listWorkspaceMembers: vi.fn() }));
vi.mock("../../components/common/V2CatalogSelector", () => ({ TaskCatalogSelector: ({ value, onChange }: { value: string; onChange: (value: string) => void }) => <label>Tarea<select aria-label="Tarea" value={value} onChange={(event) => onChange(event.target.value)}><option value="">Selecciona</option><option value="master-1">Comprar pan</option></select></label>, CategorySelector: ({ value, onChange }: { value: string; onChange: (value: string) => void }) => <label>Categoría<select aria-label="Categoría" value={value} onChange={(event) => onChange(event.target.value)}><option value="">Todas</option><option value="category-1">Casa</option></select></label> }));
const auth = { user: { id: "user-1", email: "ana@example.com", first_name: "Ana", last_name: "Uno", timezone: "America/Lima" }, workspace: { id: "workspace-a", name: "Familia", kind: "SHARED" as "SHARED" | "PERSONAL", timezone: "America/Lima" } };
vi.mock("../../hooks/useAuth", () => ({ useAuth: () => auth }));

const task = { id: "task-1", workspace_id: "workspace-a", master_task_id: "master-1", master_task_name: "Comprar pan", category_id: "category-1", category_name: "Casa", responsible_user_id: "user-1", responsible_display_name: "Ana Uno", responsible_email: "ana@example.com", planned_date: "2026-08-26", state: "PROGRAMADA" as const, result: null, resolved_at: null, resolved_by_user_id: null, lock_version: 1, is_generated: false, can_edit_this: true, can_edit_future: false, can_delete_this: true, can_delete_future: false, can_edit: true, can_resolve: false, can_delete: true, created_at: "2026-08-25T00:00:00Z", updated_at: "2026-08-25T00:00:00Z" };

function renderPage() { const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); return { ...render(<QueryClientProvider client={client}><PlanningTasksPage /></QueryClientProvider>), client }; }

describe("V2 PlanningTasksPage", () => {
  beforeEach(() => { auth.workspace = { id: "workspace-a", name: "Familia", kind: "SHARED", timezone: "America/Lima" }; vi.clearAllMocks(); vi.mocked(workspaceApi.listWorkspaceMembers).mockResolvedValue([{ user_id: "user-1", display_name: "Ana Uno", email: "ana@example.com", role: "Miembro", status: "ACTIVE", joined_at: "", ended_at: null }, { user_id: "user-2", display_name: "Luis Dos", email: "luis@example.com", role: "Miembro", status: "ACTIVE", joined_at: "", ended_at: null }]); vi.mocked(taskApi.listV2Tasks).mockResolvedValue({ items: [task], total: 1, page: 1, page_size: 25, total_pages: 1 }); vi.mocked(taskApi.createV2Task).mockResolvedValue(task); vi.mocked(taskApi.updateV2Task).mockResolvedValue(task); vi.mocked(taskApi.resolveV2Task).mockResolvedValue({ ...task, state: "COMPLETADA", result: "COMPLETED" }); vi.mocked(taskApi.deleteV2Task).mockResolvedValue(); vi.spyOn(window, "confirm").mockReturnValue(true); });

  it("creates a Shared Task with workspace-scoped MasterTask and responsible member", async () => { const user = userEvent.setup(); renderPage(); const form = screen.getByRole("heading", { name: "Crear tarea" }).closest("section")!; await user.selectOptions(within(form).getByLabelText("Tarea"), "master-1"); await user.type(within(form).getByLabelText("Fecha"), "2026-08-26"); await user.selectOptions(await within(form).findByLabelText("Responsable"), "user-2"); await user.click(within(form).getByRole("button", { name: "Crear" })); await waitFor(() => expect(taskApi.createV2Task).toHaveBeenCalledWith("workspace-a", { master_task_id: "master-1", planned_date: "2026-08-26", responsible_user_id: "user-2" })); });

  it("creates a finite WEEKLY recurrence with Monday-zero weekdays", async () => { vi.mocked(taskApi.createV2RecurringTasks).mockResolvedValue({ created_count: 2, items: [task, { ...task, id: "task-2" }] }); const user = userEvent.setup(); renderPage(); const form = screen.getByRole("heading", { name: "Crear tarea" }).closest("section")!; await user.selectOptions(within(form).getByLabelText("Tarea"), "master-1"); await user.selectOptions(within(form).getByLabelText("Tipo de creación"), "RECURRING"); await user.selectOptions(within(form).getByLabelText("Frecuencia"), "WEEKLY"); await user.type(within(form).getByLabelText("Desde"), "2026-08-17"); await user.type(within(form).getByLabelText("Hasta"), "2026-08-23"); await user.click(within(form).getByLabelText("Lunes")); await user.click(within(form).getByLabelText("Miércoles")); await user.selectOptions(await within(form).findByLabelText("Responsable"), "user-2"); expect(within(form).getByText("Se crearán 2 tareas.")).toBeInTheDocument(); await user.click(within(form).getByRole("button", { name: "Crear" })); await waitFor(() => expect(taskApi.createV2RecurringTasks).toHaveBeenCalledWith("workspace-a", { master_task_id: "master-1", responsible_user_id: "user-2", recurrence: { pattern: "WEEKLY", date_from: "2026-08-17", date_until: "2026-08-23", weekdays: [0, 2] } })); expect(await screen.findByText("Se crearon 2 tareas.")).toBeInTheDocument(); });

  it("supports multiple MONTHLY anchors and explains month-end fallback", async () => { const user = userEvent.setup(); renderPage(); const form = screen.getByRole("heading", { name: "Crear tarea" }).closest("section")!; await user.selectOptions(within(form).getByLabelText("Tipo de creación"), "RECURRING"); await user.selectOptions(within(form).getByLabelText("Frecuencia"), "MONTHLY"); await user.type(within(form).getByLabelText("Desde"), "2027-02-01"); await user.type(within(form).getByLabelText("Hasta"), "2027-02-28"); await user.type(within(form).getByLabelText("Días del mes"), "29, 30, 31"); expect(within(form).getByText("Si el día no existe en un mes, se usará el último día de ese mes.")).toBeInTheDocument(); expect(within(form).getByText("Se crearán 1 tareas.")).toBeInTheDocument(); });

  it("requires valid finite recurrence boundaries", async () => { const user = userEvent.setup(); renderPage(); const form = screen.getByRole("heading", { name: "Crear tarea" }).closest("section")!; await user.selectOptions(within(form).getByLabelText("Tarea"), "master-1"); await user.selectOptions(within(form).getByLabelText("Tipo de creación"), "RECURRING"); await user.type(within(form).getByLabelText("Desde"), "2026-08-24"); await user.type(within(form).getByLabelText("Hasta"), "2026-08-17"); await user.selectOptions(await within(form).findByLabelText("Responsable"), "user-2"); await user.click(within(form).getByRole("button", { name: "Crear" })); expect(await screen.findByRole("alert")).toHaveTextContent("Completa correctamente"); expect(taskApi.createV2RecurringTasks).not.toHaveBeenCalled(); });

  it("omits responsible_user_id for Personal recurrence", async () => { auth.workspace = { id: "personal-a", name: "Personal", kind: "PERSONAL", timezone: "America/Lima" }; vi.mocked(taskApi.createV2RecurringTasks).mockResolvedValue({ created_count: 1, items: [task] }); const user = userEvent.setup(); renderPage(); const form = screen.getByRole("heading", { name: "Crear tarea" }).closest("section")!; await user.selectOptions(within(form).getByLabelText("Tarea"), "master-1"); await user.selectOptions(within(form).getByLabelText("Tipo de creación"), "RECURRING"); await user.type(within(form).getByLabelText("Desde"), "2026-08-26"); await user.type(within(form).getByLabelText("Hasta"), "2026-08-26"); await user.click(within(form).getByRole("button", { name: "Crear" })); await waitFor(() => expect(taskApi.createV2RecurringTasks).toHaveBeenCalledWith("personal-a", { master_task_id: "master-1", recurrence: { pattern: "DAILY", date_from: "2026-08-26", date_until: "2026-08-26" } })); });

  it("renders a future derived state without premature resolution actions", async () => { renderPage(); const table = await screen.findByRole("table", { name: "Tareas planificadas" }); expect(within(table).getByText("Programada")).toBeInTheDocument(); expect(within(table).getByText("Ana Uno")).toBeInTheDocument(); expect(within(table).queryByRole("button", { name: "Completado" })).not.toBeInTheDocument(); });

  it("edits all approved standalone fields with lock_version", async () => { const user = userEvent.setup(); renderPage(); await user.click(await screen.findByRole("button", { name: "Editar Comprar pan" })); await user.selectOptions(screen.getAllByLabelText("Responsable").at(-1)!, "user-2"); await user.click(screen.getByRole("button", { name: "Guardar" })); await waitFor(() => expect(taskApi.updateV2Task).toHaveBeenCalledWith("workspace-a", "task-1", { master_task_id: "master-1", planned_date: "2026-08-26", responsible_user_id: "user-2", lock_version: 1, scope: "THIS" })); });

  it("uses workspace-scoped cache and clears edit state on conflict", async () => { vi.mocked(taskApi.updateV2Task).mockRejectedValue({ isAxiosError: true, response: { status: 409 } }); const user = userEvent.setup(); renderPage(); await user.click(await screen.findByRole("button", { name: "Editar Comprar pan" })); await user.click(screen.getByRole("button", { name: "Guardar" })); expect(await screen.findByRole("alert")).toHaveTextContent("La tarea cambió"); await waitFor(() => expect(screen.queryByRole("dialog")).not.toBeInTheDocument()); expect(taskApi.listV2Tasks).toHaveBeenCalledWith("workspace-a", { page: 1, page_size: 25 }); });

  it("deletes only when server-projected action is available", async () => { const user = userEvent.setup(); renderPage(); await user.click(await screen.findByRole("button", { name: "Eliminar Comprar pan" })); await waitFor(() => expect(taskApi.deleteV2Task).toHaveBeenCalledWith("workspace-a", "task-1", 1, "THIS")); });

  it("asks scope only for a generated future Task and edits all future occurrences", async () => { vi.mocked(taskApi.listV2Tasks).mockResolvedValue({ items: [{ ...task, is_generated: true, can_edit_future: true, can_delete_future: true }], total: 1, page: 1, page_size: 25, total_pages: 1 }); const user = userEvent.setup(); renderPage(); await user.click(await screen.findByRole("button", { name: "Editar Comprar pan" })); expect(screen.getByRole("heading", { name: "Elegir alcance" })).toBeInTheDocument(); await user.click(screen.getByRole("button", { name: "Todas las futuras" })); const dialog = screen.getByRole("dialog"); expect(within(dialog).queryByLabelText("Fecha")).not.toBeInTheDocument(); await user.selectOptions(within(dialog).getByLabelText("Responsable"), "user-2"); await user.click(within(dialog).getByRole("button", { name: "Guardar" })); await waitFor(() => expect(taskApi.updateV2Task).toHaveBeenCalledWith("workspace-a", "task-1", { master_task_id: "master-1", responsible_user_id: "user-2", lock_version: 1, scope: "THIS_AND_FUTURE" })); });

  it("deletes generated THIS_AND_FUTURE through the explicit scope", async () => { vi.mocked(taskApi.listV2Tasks).mockResolvedValue({ items: [{ ...task, is_generated: true, can_edit_future: true, can_delete_future: true }], total: 1, page: 1, page_size: 25, total_pages: 1 }); const user = userEvent.setup(); renderPage(); await user.click(await screen.findByRole("button", { name: "Eliminar Comprar pan" })); await user.click(screen.getByRole("button", { name: "Todas las futuras" })); await waitFor(() => expect(taskApi.deleteV2Task).toHaveBeenCalledWith("workspace-a", "task-1", 1, "THIS_AND_FUTURE")); });

  it("edits and deletes only the selected generated occurrence when Solo esta is chosen", async () => { vi.mocked(taskApi.listV2Tasks).mockResolvedValue({ items: [{ ...task, is_generated: true, can_edit_future: true, can_delete_future: true }], total: 1, page: 1, page_size: 25, total_pages: 1 }); const user = userEvent.setup(); renderPage(); await user.click(await screen.findByRole("button", { name: "Editar Comprar pan" })); await user.click(screen.getByRole("button", { name: "Solo esta" })); const editDialog = screen.getByRole("dialog"); expect(within(editDialog).getByLabelText("Fecha")).toBeInTheDocument(); await user.click(within(editDialog).getByRole("button", { name: "Guardar" })); await waitFor(() => expect(taskApi.updateV2Task).toHaveBeenCalledWith("workspace-a", "task-1", expect.objectContaining({ planned_date: "2026-08-26", scope: "THIS" }))); await user.click(await screen.findByRole("button", { name: "Eliminar Comprar pan" })); await user.click(screen.getByRole("button", { name: "Solo esta" })); await waitFor(() => expect(taskApi.deleteV2Task).toHaveBeenCalledWith("workspace-a", "task-1", 1, "THIS")); });

  it("clears a generated scope dialog when Workspace changes", async () => { vi.mocked(taskApi.listV2Tasks).mockResolvedValue({ items: [{ ...task, is_generated: true, can_edit_future: true, can_delete_future: true }], total: 1, page: 1, page_size: 25, total_pages: 1 }); const user = userEvent.setup(); const view = renderPage(); await user.click(await screen.findByRole("button", { name: "Editar Comprar pan" })); expect(screen.getByRole("heading", { name: "Elegir alcance" })).toBeInTheDocument(); auth.workspace = { id: "workspace-b", name: "Otro", kind: "SHARED", timezone: "America/Lima" }; view.rerender(<QueryClientProvider client={view.client}><PlanningTasksPage /></QueryClientProvider>); await waitFor(() => expect(screen.queryByRole("heading", { name: "Elegir alcance" })).not.toBeInTheDocument()); });

  it("shows Editar only for future Programada tasks and keeps Pendiente resolution actions", async () => {
    vi.mocked(taskApi.listV2Tasks).mockResolvedValue({
      items: [
        task,
        { ...task, id: "today", master_task_name: "Tarea de hoy", planned_date: "2026-08-25", state: "PENDIENTE", can_edit_this: false, can_edit_future: false, can_delete_this: false, can_delete_future: false, can_edit: false, can_resolve: true, can_delete: false },
        { ...task, id: "overdue", master_task_name: "Tarea vencida", planned_date: "2026-08-24", state: "PENDIENTE", can_edit_this: false, can_edit_future: false, can_delete_this: false, can_delete_future: false, can_edit: false, can_resolve: true, can_delete: false }
      ],
      total: 3, page: 1, page_size: 25, total_pages: 1
    });
    renderPage();
    expect(await screen.findByRole("button", { name: "Editar Comprar pan" })).toBeInTheDocument();
    expect(screen.queryByRole("button", { name: "Editar Tarea de hoy" })).not.toBeInTheDocument();
    expect(screen.queryByRole("button", { name: "Editar Tarea vencida" })).not.toBeInTheDocument();
    expect(screen.getAllByRole("button", { name: "Completado" })).toHaveLength(2);
  });

  it("keeps resolved Tasks read-only", async () => { vi.mocked(taskApi.listV2Tasks).mockResolvedValue({ items: [{ ...task, state: "COMPLETADA", result: "COMPLETED", can_edit_this: false, can_edit_future: false, can_delete_this: false, can_delete_future: false, can_edit: false, can_resolve: false, can_delete: false }], total: 1, page: 1, page_size: 25, total_pages: 1 }); renderPage(); await screen.findByText("Completada"); expect(screen.queryByRole("button", { name: /Editar/ })).not.toBeInTheDocument(); expect(screen.queryByRole("button", { name: /Eliminar/ })).not.toBeInTheDocument(); });
});
