import axios from "axios";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState, type FormEvent } from "react";
import { Link } from "react-router-dom";

import { queryKeys } from "../../api/queryKeys";
import { configureV2ProjectStages, listV2ProjectStages, reorderV2ProjectStages } from "../../api/v2ProjectStageApi";
import type { WorkspaceMemberSummary } from "../../api/workspaceApi";
import type { V2Project } from "../../types/v2Project";
import type { V2ProjectStage, V2ProjectStageConfigurationItem } from "../../types/v2ProjectStage";
import { formatShortCalendarDate } from "../../utils/localizedDate";

const labels: Record<string, string> = { NO_INICIADA: "No iniciada", EN_PROCESO: "En proceso", FINALIZADA: "Finalizada", EN_PLAZO: "En plazo", ATRASADO: "Atrasada", A_TIEMPO: "A tiempo", CON_ADELANTO: "Con adelanto", CON_RETRASO: "Con retraso" };
const decimal = (value: string) => Math.round(Number(value) * 100);

export function ProjectStagesPanel({ workspaceId, project, shared, members, basePath = "/planificacion/proyectos", editable = true }: { workspaceId: string; project: V2Project; shared: boolean; members: WorkspaceMemberSummary[]; basePath?: string; editable?: boolean }) {
  const client = useQueryClient();
  const [name, setName] = useState(""); const [responsible, setResponsible] = useState(""); const [date, setDate] = useState(""); const [weight, setWeight] = useState("");
  const [editing, setEditing] = useState<V2ProjectStage | null>(null); const [draftConfiguration, setDraftConfiguration] = useState<V2ProjectStageConfigurationItem[] | null>(null); const [feedback, setFeedback] = useState<string | null>(null);
  const stages = useQuery({ queryKey: queryKeys.v2ProjectStages(workspaceId, project.id), queryFn: () => listV2ProjectStages(workspaceId, project.id) });
  const refresh = async () => { await Promise.all([client.invalidateQueries({ queryKey: queryKeys.v2ProjectStages(workspaceId, project.id) }), client.invalidateQueries({ queryKey: queryKeys.v2ProjectDetail(workspaceId, project.id) }), client.invalidateQueries({ queryKey: queryKeys.v2ProjectsRoot(workspaceId) })]); };
  const mutation = useMutation({ mutationFn: (operation: () => Promise<unknown>) => operation(), onSuccess: async () => { setEditing(null); setDraftConfiguration(null); setName(""); setDate(""); setWeight(""); setFeedback("Etapas guardadas."); await refresh(); }, onError: async (error) => { setEditing(null); setDraftConfiguration(null); setFeedback(axios.isAxiosError(error) && error.response?.status === 409 ? "Las Etapas o el Proyecto cambiaron. Actualizamos los datos; vuelve a intentarlo." : "No pudimos guardar las Etapas."); await refresh(); } });
  const items = stages.data?.items ?? [];
  const configured = (stage: V2ProjectStage): V2ProjectStageConfigurationItem => ({ id: stage.id, responsible_user_id: stage.responsible_user_id, name: stage.name, weight: stage.weight, planned_date: stage.planned_date, lock_version: stage.lock_version });
  function saveConfiguration(configuration: V2ProjectStageConfigurationItem[]) {
    if (configuration.reduce((sum, item) => sum + decimal(item.weight), 0) !== 10000) { setFeedback("La configuración debe sumar exactamente 100.00%."); return; }
    mutation.mutate(() => configureV2ProjectStages(workspaceId, project.id, { items: configuration, project_lock_version: project.lock_version }));
  }
  function create(event: FormEvent) { event.preventDefault(); const next = [...items.map(configured), { ...(shared ? { responsible_user_id: responsible } : {}), name: name.trim(), weight, planned_date: date }]; if (next.reduce((sum, item) => sum + decimal(item.weight), 0) === 10000) saveConfiguration(next); else { setDraftConfiguration(next); setFeedback("Ajusta los pesos de toda la configuración hasta 100.00%."); } }
  function move(index: number, offset: -1 | 1) { const reordered = [...items]; const [stage] = reordered.splice(index, 1); reordered.splice(index + offset, 0, stage); mutation.mutate(() => reorderV2ProjectStages(workspaceId, project.id, { items: reordered.map((item) => ({ id: item.id, lock_version: item.lock_version })), project_lock_version: project.lock_version })); }
  return <section className="project-stages"><h3>Etapas</h3>{feedback ? <p role="status">{feedback}</p> : null}
    <div className={stages.data?.weights_complete ? "stage-weight-summary" : "stage-weight-summary stage-weight-summary--incomplete"}><strong>Peso total: {stages.data?.total_weight ?? "0.00"}%</strong><span>{stages.data?.weights_complete ? "Configuración completa" : "La suma debe ser exactamente 100.00% para guardar la configuración."}</span></div>
    {stages.isPending ? <p>Cargando Etapas…</p> : stages.isError ? <button type="button" onClick={() => void stages.refetch()}>Reintentar</button> : <div className="project-stage-list">{items.map((stage, index) => <article key={stage.id}><strong>{index + 1}. {stage.name}</strong><span>{stage.responsible_display_name}</span><span>Peso {stage.weight}%</span><span>{formatShortCalendarDate(stage.planned_date)}</span><span>Avance {stage.progress}% · {labels[stage.state]}</span><span>{labels[stage.compliance]} · {stage.compliance_detail_days} días</span><div><Link className="compact-link" aria-label={`Abrir Etapa ${stage.name}`} to={`${basePath}/${project.id}/etapas/${stage.id}`}>›</Link>{editable && project.is_active ? <><button type="button" aria-label={`Subir Etapa ${stage.name}`} disabled={index === 0 || mutation.isPending} onClick={() => move(index, -1)}>↑</button><button type="button" aria-label={`Bajar Etapa ${stage.name}`} disabled={index === items.length - 1 || mutation.isPending} onClick={() => move(index, 1)}>↓</button></> : null}{editable && stage.can_edit ? <button type="button" onClick={() => setEditing(stage)}>Editar</button> : null}</div></article>)}</div>}
    {editable && project.is_active ? <><form className="project-stage-form" onSubmit={create}><h4>Agregar Etapa</h4><label>Nombre<input required maxLength={255} value={name} onChange={(event) => setName(event.target.value)} /></label>{shared ? <label>Responsable<select required value={responsible} onChange={(event) => setResponsible(event.target.value)}><option value="">Selecciona</option>{members.map((member) => <option key={member.user_id} value={member.user_id}>{member.display_name}</option>)}</select></label> : null}<label>Fecha planificada<input required type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label><label>Peso (%)<input required type="number" min="0.01" max="100" step="0.01" value={weight} onChange={(event) => setWeight(event.target.value)} /></label><button disabled={mutation.isPending}>Agregar</button></form>{items.length ? <button type="button" onClick={() => setDraftConfiguration(items.map(configured))}>Configurar pesos</button> : null}</> : <p>Reactiva el Proyecto para modificar sus Etapas.</p>}
    {editing ? <dialog open><form onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); saveConfiguration(items.map((stage) => stage.id === editing.id ? { ...configured(stage), name: String(data.get("name")), responsible_user_id: shared ? String(data.get("responsible")) : stage.responsible_user_id, planned_date: String(data.get("date")), weight: String(data.get("weight")) } : configured(stage))); }}><h3>Editar Etapa</h3><label>Nombre<input name="name" required defaultValue={editing.name} /></label>{shared ? <label>Responsable<select name="responsible" defaultValue={editing.responsible_user_id}>{members.map((member) => <option key={member.user_id} value={member.user_id}>{member.display_name}</option>)}</select></label> : null}<label>Fecha planificada<input name="date" type="date" required defaultValue={editing.planned_date} /></label><label>Peso (%)<input name="weight" type="number" min="0.01" max="100" step="0.01" defaultValue={editing.weight} /></label><button>Guardar configuración</button><button type="button" onClick={() => setEditing(null)}>Cancelar</button></form></dialog> : null}
    {draftConfiguration ? <dialog open><form onSubmit={(event) => { event.preventDefault(); saveConfiguration(draftConfiguration); }}><h3>Configurar pesos</h3>{draftConfiguration.map((item, index) => <label key={item.id ?? `new-${index}`}>{item.name}<input aria-label={`Peso de ${item.name}`} required type="number" min="0.01" max="100" step="0.01" value={item.weight} onChange={(event) => setDraftConfiguration((current) => current?.map((entry, entryIndex) => entryIndex === index ? { ...entry, weight: event.target.value } : entry) ?? null)} /></label>)}<p><strong>Total: {(draftConfiguration.reduce((sum, item) => sum + decimal(item.weight), 0) / 100).toFixed(2)}%</strong></p><button disabled={draftConfiguration.reduce((sum, item) => sum + decimal(item.weight), 0) !== 10000 || mutation.isPending}>Guardar configuración</button><button type="button" onClick={() => setDraftConfiguration(null)}>Cancelar</button></form></dialog> : null}
  </section>;
}
