import axios from "axios";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState, type FormEvent } from "react";
import { queryKeys } from "../../api/queryKeys";
import { createV2ProjectStage, listV2ProjectStages, updateV2ProjectStage, updateV2ProjectStageProgress } from "../../api/v2ProjectStageApi";
import type { WorkspaceMemberSummary } from "../../api/workspaceApi";
import type { V2Project } from "../../types/v2Project";
import type { V2ProjectStage } from "../../types/v2ProjectStage";

export function ProjectStagesPanel({ workspaceId, project, shared, members }: { workspaceId: string; project: V2Project; shared: boolean; members: WorkspaceMemberSummary[] }) {
  const client = useQueryClient(); const [name, setName] = useState(""); const [responsible, setResponsible] = useState(""); const [date, setDate] = useState(""); const [weight, setWeight] = useState(""); const [editing, setEditing] = useState<V2ProjectStage | null>(null); const [feedback, setFeedback] = useState<string | null>(null);
  const stages = useQuery({ queryKey: queryKeys.v2ProjectStages(workspaceId, project.id), queryFn: () => listV2ProjectStages(workspaceId, project.id) });
  const refresh = async () => { await Promise.all([client.invalidateQueries({ queryKey: queryKeys.v2ProjectStages(workspaceId, project.id) }), client.invalidateQueries({ queryKey: queryKeys.v2ProjectDetail(workspaceId, project.id) }), client.invalidateQueries({ queryKey: queryKeys.v2ProjectsRoot(workspaceId) })]); };
  const mutation = useMutation({ mutationFn: (operation: () => Promise<unknown>) => operation(), onSuccess: async () => { setEditing(null); setFeedback("Etapa guardada."); await refresh(); }, onError: async (error) => { setEditing(null); setFeedback(axios.isAxiosError(error) && error.response?.status === 409 ? "La Etapa o el Proyecto cambió. Actualizamos los datos; vuelve a intentarlo." : "No pudimos guardar la Etapa."); await refresh(); } });
  function create(event: FormEvent) { event.preventDefault(); mutation.mutate(() => createV2ProjectStage(workspaceId, project.id, { ...(shared ? { responsible_user_id: responsible } : {}), name: name.trim(), position: stages.data?.items.length ?? 0, weight, planned_date: date, project_lock_version: project.lock_version }).then((value) => { setName(""); setDate(""); setWeight(""); return value; })); }
  const labels = { NO_INICIADA: "No iniciada", EN_PROCESO: "En proceso", FINALIZADA: "Finalizada", EN_PLAZO: "En plazo", ATRASADO: "Atrasada", A_TIEMPO: "A tiempo", CON_ADELANTO: "Con adelanto", CON_RETRASO: "Con retraso" };
  return <section className="project-stages"><h3>Etapas</h3>{feedback ? <p role="status">{feedback}</p> : null}<div className={stages.data?.weights_complete ? "stage-weight-summary" : "stage-weight-summary stage-weight-summary--incomplete"}><strong>Peso total: {stages.data?.total_weight ?? "0"}%</strong><span>{stages.data?.weights_complete ? "Configuración completa" : "La suma debe llegar exactamente a 100% para calcular el avance global."}</span></div>{stages.isPending ? <p>Cargando Etapas…</p> : stages.isError ? <button type="button" onClick={() => void stages.refetch()}>Reintentar</button> : <div className="project-stage-list">{stages.data.items.map((stage) => <article key={stage.id}><strong>{stage.name}</strong><span>{stage.responsible_display_name}</span><span>Peso {stage.weight}%</span><span>Avance {stage.progress}% · {labels[stage.state]}</span><span>{labels[stage.compliance]} · {stage.compliance_detail_days} días</span><div>{stage.can_edit ? <button type="button" onClick={() => setEditing(stage)}>Editar</button> : null}{stage.can_update_progress ? <button type="button" onClick={() => { const value = window.prompt("Nuevo avance (0-100)", String(stage.progress)); if (value !== null) mutation.mutate(() => updateV2ProjectStageProgress(workspaceId, project.id, stage.id, Number(value), stage.lock_version, project.lock_version)); }}>Avance</button> : null}</div></article>)}</div>}
    {project.is_active ? <form className="project-stage-form" onSubmit={create}><h4>Agregar Etapa</h4><label>Nombre<input required maxLength={255} value={name} onChange={(event) => setName(event.target.value)} /></label>{shared ? <label>Responsable<select required value={responsible} onChange={(event) => setResponsible(event.target.value)}><option value="">Selecciona</option>{members.map((member) => <option key={member.user_id} value={member.user_id}>{member.display_name}</option>)}</select></label> : null}<label>Fecha planificada<input required type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label><label>Peso (%)<input required type="number" min="0.01" max="100" step="0.01" value={weight} onChange={(event) => setWeight(event.target.value)} /></label><button disabled={mutation.isPending}>Agregar</button></form> : null}
    {editing ? <dialog open><form onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); mutation.mutate(() => updateV2ProjectStage(workspaceId, project.id, editing.id, { name: String(data.get("name")), responsible_user_id: shared ? String(data.get("responsible")) : editing.responsible_user_id, planned_date: String(data.get("date")), weight: String(data.get("weight")), position: editing.position, lock_version: editing.lock_version, project_lock_version: project.lock_version })); }}><h3>Editar Etapa</h3><label>Nombre<input name="name" required defaultValue={editing.name} /></label>{shared ? <label>Responsable<select name="responsible" defaultValue={editing.responsible_user_id}>{members.map((member) => <option key={member.user_id} value={member.user_id}>{member.display_name}</option>)}</select></label> : null}<label>Fecha planificada<input name="date" type="date" required defaultValue={editing.planned_date} /></label><label>Peso (%)<input name="weight" type="number" min="0.01" max="100" step="0.01" defaultValue={editing.weight} /></label><button>Guardar</button><button type="button" onClick={() => setEditing(null)}>Cancelar</button></form></dialog> : null}</section>;
}
