import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { useMemo, useState, type PropsWithChildren } from "react";
import { MemoryRouter } from "react-router-dom";
import { beforeEach, describe, expect, it, vi } from "vitest";

import * as userSettingsApi from "../../api/userSettingsApi";
import * as workspaceApi from "../../api/workspaceApi";
import * as workspaceSettingsApi from "../../api/workspaceSettingsApi";
import { useAuth } from "../../hooks/useAuth";
import { AuthContext, type AuthState } from "../../store/auth-context";
import { testUser } from "../../test/testUser";
import type { WorkspaceSummary } from "../../types/auth";
import type { UserSettings, WorkspaceSettings } from "../../types/settings";
import { SettingsPage } from "./SettingsPage";

vi.mock("../../api/workspaceApi", () => ({ listWorkspaces: vi.fn() }));
vi.mock("../../api/userSettingsApi", () => ({ getUserSettings: vi.fn(), updateUserSettings: vi.fn() }));
vi.mock("../../api/workspaceSettingsApi", () => ({ getWorkspaceSettings: vi.fn(), updateWorkspaceSettings: vi.fn() }));

const workspace: WorkspaceSummary = { id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa", name: "Personal", description: null, timezone: "America/Lima", created_at: "2026-08-01T00:00:00Z", updated_at: "2026-08-01T00:00:00Z" };
const otherWorkspace = { ...workspace, id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb", name: "Trabajo" };
const userSettings: UserSettings = { id: "10000000-0000-4000-8000-000000000000", user_id: testUser.id, timezone: "America/Lima", locale: "es-PE", week_starts_on: "MONDAY", daily_form_reminders_enabled: true, task_due_reminders_enabled: true, task_overdue_reminders_enabled: false, daily_form_reminder_time: "09:00:00", task_due_reminder_minutes: 60, created_at: "2026-08-01T00:00:00Z", updated_at: "2026-08-01T00:00:00Z" };
const workspaceSettings: WorkspaceSettings = { id: "20000000-0000-4000-8000-000000000000", workspace_id: workspace.id, timezone: "America/Lima", daily_form_enabled: true, daily_form_reminder_time: "09:00:00", daily_task_generation_enabled: true, week_starts_on: "MONDAY", created_at: "2026-08-01T00:00:00Z", updated_at: "2026-08-01T00:00:00Z" };

function Auth({ children, initial = workspace }: PropsWithChildren<{ initial?: WorkspaceSummary | null }>) { const [selected, setWorkspace] = useState(initial); const value = useMemo<AuthState>(() => ({ user: testUser, workspace: selected, isAuthenticated: true, isInitializing: false, login: vi.fn(), logout: vi.fn(), setWorkspace, clearSession: vi.fn(), setAuthenticatedUser: vi.fn() }), [selected]); return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>; }
function Switcher() { const { setWorkspace } = useAuth(); return <button onClick={() => setWorkspace(otherWorkspace)}>Cambiar espacio</button>; }
function renderPage(initial: WorkspaceSummary | null = workspace, switcher = false) { const client = new QueryClient({ defaultOptions: { queries: { retry: false, gcTime: Infinity }, mutations: { retry: false } } }); render(<QueryClientProvider client={client}><Auth initial={initial}><MemoryRouter>{switcher && <Switcher />}<SettingsPage /></MemoryRouter></Auth></QueryClientProvider>); return client; }

describe("SettingsPage", () => {
  beforeEach(() => { vi.clearAllMocks(); vi.mocked(workspaceApi.listWorkspaces).mockResolvedValue([workspace]); vi.mocked(userSettingsApi.getUserSettings).mockResolvedValue(userSettings); vi.mocked(userSettingsApi.updateUserSettings).mockResolvedValue(userSettings); vi.mocked(workspaceSettingsApi.getWorkspaceSettings).mockResolvedValue(workspaceSettings); vi.mocked(workspaceSettingsApi.updateWorkspaceSettings).mockResolvedValue(workspaceSettings); });

  it("loads and renders real User Settings defaults", async () => { renderPage(); expect(await screen.findByLabelText("Zona horaria")).toHaveValue("America/Lima"); expect(screen.getByLabelText("Configuración regional")).toHaveValue("es-PE"); expect(screen.getByLabelText("Primer día de la semana", { selector: "select#user-week-start" })).toHaveValue("MONDAY"); expect(screen.getByLabelText("Formulario diario", { selector: "input" })).toBeChecked(); expect(screen.getByLabelText("Tareas vencidas")).not.toBeChecked(); });
  it("submits the complete User Settings replacement with independent toggles", async () => { const user = userEvent.setup(); renderPage(); await screen.findByLabelText("Zona horaria"); await user.clear(screen.getByLabelText("Zona horaria")); await user.type(screen.getByLabelText("Zona horaria"), "America/Bogota"); await user.clear(screen.getByLabelText("Configuración regional")); await user.type(screen.getByLabelText("Configuración regional"), "es-CO"); await user.selectOptions(screen.getByLabelText("Primer día de la semana", { selector: "select#user-week-start" }), "SUNDAY"); await user.click(screen.getByLabelText("Formulario diario", { selector: "input" })); await user.click(screen.getByLabelText("Tareas vencidas")); await user.clear(screen.getByLabelText("Hora del recordatorio diario")); await user.type(screen.getByLabelText("Hora del recordatorio diario"), "08:30"); await user.clear(screen.getByLabelText("Anticipación de tareas (minutos)")); await user.type(screen.getByLabelText("Anticipación de tareas (minutos)"), "0"); await user.click(screen.getByRole("button", { name: "Guardar preferencias" })); await waitFor(() => expect(vi.mocked(userSettingsApi.updateUserSettings).mock.calls[0]?.[0]).toEqual({ timezone: "America/Bogota", locale: "es-CO", week_starts_on: "SUNDAY", daily_form_reminders_enabled: false, task_due_reminders_enabled: true, task_overdue_reminders_enabled: true, daily_form_reminder_time: "08:30", task_due_reminder_minutes: 0 })); });
  it("accepts reminder boundaries and rejects values outside 0 through 1440", async () => { const user = userEvent.setup(); renderPage(); const input = await screen.findByLabelText("Anticipación de tareas (minutos)"); await user.clear(input); await user.type(input, "1440"); await user.click(screen.getByRole("button", { name: "Guardar preferencias" })); await waitFor(() => expect(vi.mocked(userSettingsApi.updateUserSettings).mock.calls[0]?.[0]).toEqual(expect.objectContaining({ task_due_reminder_minutes: 1440 }))); await user.clear(input); await user.type(input, "1441"); await user.click(screen.getByRole("button", { name: "Guardar preferencias" })); expect(await screen.findByText("El máximo es 1440.")).toBeInTheDocument(); });
  it("shows User save success and preserves values after failure", async () => { vi.mocked(userSettingsApi.updateUserSettings).mockRejectedValue({ isAxiosError: true, response: { status: 422 } }); const user = userEvent.setup(); renderPage(); const locale = await screen.findByLabelText("Configuración regional"); await user.clear(locale); await user.type(locale, "es-MX"); await user.click(screen.getByRole("button", { name: "Guardar preferencias" })); expect(await screen.findByText(/Revisa los valores/)).toBeInTheDocument(); expect(locale).toHaveValue("es-MX"); });

  it("loads Workspace Settings only for the selected Workspace", async () => { renderPage(); expect(await screen.findByLabelText("Zona horaria del espacio")).toHaveValue("America/Lima"); expect(workspaceSettingsApi.getWorkspaceSettings).toHaveBeenCalledWith(workspace.id); });
  it("does not request Workspace Settings without a Workspace while personal settings still load", async () => { vi.mocked(workspaceApi.listWorkspaces).mockResolvedValue([]); renderPage(null); expect(await screen.findByText("No hay un espacio de trabajo seleccionado.")).toBeInTheDocument(); expect(screen.getByLabelText("Zona horaria")).toBeInTheDocument(); expect(workspaceSettingsApi.getWorkspaceSettings).not.toHaveBeenCalled(); });
  it("isolates Workspace Settings when switching Workspaces", async () => { vi.mocked(workspaceApi.listWorkspaces).mockResolvedValue([workspace, otherWorkspace]); vi.mocked(workspaceSettingsApi.getWorkspaceSettings).mockImplementation(async (id) => ({ ...workspaceSettings, workspace_id: id, timezone: id === otherWorkspace.id ? "Europe/Madrid" : "America/Lima" })); const user = userEvent.setup(); renderPage(workspace, true); expect(await screen.findByLabelText("Zona horaria del espacio")).toHaveValue("America/Lima"); await user.click(screen.getByRole("button", { name: "Cambiar espacio" })); await waitFor(() => expect(workspaceSettingsApi.getWorkspaceSettings).toHaveBeenCalledWith(otherWorkspace.id)); await waitFor(() => expect(screen.getByLabelText("Zona horaria del espacio")).toHaveValue("Europe/Madrid")); });
  it("submits a full Workspace replacement and explains disabled behavior", async () => { const user = userEvent.setup(); renderPage(); await screen.findByLabelText("Zona horaria del espacio"); await user.clear(screen.getByLabelText("Zona horaria del espacio")); await user.type(screen.getByLabelText("Zona horaria del espacio"), "Europe/Madrid"); await user.click(screen.getByLabelText("Habilitar Formulario diario")); expect(screen.getByText(/La hora se conserva/)).toBeInTheDocument(); await user.click(screen.getByLabelText("Habilitar generación diaria de tareas")); expect(screen.getByText(/no generará tareas recurrentes/)).toBeInTheDocument(); await user.selectOptions(screen.getByLabelText("Primer día de la semana", { selector: "select#workspace-week-start" }), "SUNDAY"); await user.click(screen.getByRole("button", { name: "Guardar configuración del espacio" })); await waitFor(() => expect(workspaceSettingsApi.updateWorkspaceSettings).toHaveBeenCalledWith(workspace.id, { timezone: "Europe/Madrid", daily_form_enabled: false, daily_form_reminder_time: "09:00", daily_task_generation_enabled: false, week_starts_on: "SUNDAY" })); });
  it("shows Workspace save success using the server response", async () => { vi.mocked(workspaceSettingsApi.updateWorkspaceSettings).mockResolvedValue({ ...workspaceSettings, timezone: "Etc/UTC", updated_at: "2026-08-07T12:00:00Z" }); const user = userEvent.setup(); renderPage(); await screen.findByLabelText("Zona horaria del espacio"); await user.clear(screen.getByLabelText("Zona horaria del espacio")); await user.type(screen.getByLabelText("Zona horaria del espacio"), "UTC"); await user.click(screen.getByRole("button", { name: "Guardar configuración del espacio" })); expect(await screen.findByText("Configuración del espacio actualizada.")).toBeInTheDocument(); expect(screen.getByLabelText("Zona horaria del espacio")).toHaveValue("Etc/UTC"); });
  it("shows an authorization error after a 403 while preserving values and allowing retries", async () => { vi.mocked(workspaceSettingsApi.updateWorkspaceSettings).mockRejectedValueOnce({ isAxiosError: true, response: { status: 403 } }).mockResolvedValueOnce({ ...workspaceSettings, timezone: "Europe/Madrid" }); const user = userEvent.setup(); renderPage(); const timezone = await screen.findByLabelText("Zona horaria del espacio"); await user.clear(timezone); await user.type(timezone, "Europe/Madrid"); const save = screen.getByRole("button", { name: "Guardar configuración del espacio" }); await user.click(save); expect(await screen.findByText("No tienes permisos para modificar la configuración del espacio.")).toBeInTheDocument(); expect(timezone).toHaveValue("Europe/Madrid"); expect(timezone).toBeEnabled(); expect(save).toBeEnabled(); await user.click(save); expect(await screen.findByText("Configuración del espacio actualizada.")).toBeInTheDocument(); expect(workspaceSettingsApi.updateWorkspaceSettings).toHaveBeenCalledTimes(2); });
  it("preserves Workspace form values after validation failure", async () => { vi.mocked(workspaceSettingsApi.updateWorkspaceSettings).mockRejectedValue({ isAxiosError: true, response: { status: 422 } }); const user = userEvent.setup(); renderPage(); const timezone = await screen.findByLabelText("Zona horaria del espacio"); await user.clear(timezone); await user.type(timezone, "Invalid/Zone"); await user.click(screen.getByRole("button", { name: "Guardar configuración del espacio" })); expect(await screen.findByText(/Revisa los valores/)).toBeInTheDocument(); expect(timezone).toHaveValue("Invalid/Zone"); });
  it("keeps User and Workspace saves independent and does not invalidate the Workspace list", async () => { const user = userEvent.setup(); const client = renderPage(); const invalidate = vi.spyOn(client, "invalidateQueries"); await screen.findByLabelText("Zona horaria"); await user.click(screen.getByRole("button", { name: "Guardar preferencias" })); await user.click(screen.getByRole("button", { name: "Guardar configuración del espacio" })); await waitFor(() => expect(userSettingsApi.updateUserSettings).toHaveBeenCalledTimes(1)); expect(workspaceSettingsApi.updateWorkspaceSettings).toHaveBeenCalledTimes(1); expect(invalidate).not.toHaveBeenCalledWith({ queryKey: ["workspaces"] }); });
});
