import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { useMemo, useState, type PropsWithChildren } from "react";
import { MemoryRouter } from "react-router-dom";
import { beforeEach, describe, expect, it, vi } from "vitest";

import * as formApi from "../../api/dailyFormApi";
import * as workflowApi from "../../api/dailyWorkflowApi";
import * as workspaceApi from "../../api/workspaceApi";
import { useAuth } from "../../hooks/useAuth";
import { AuthContext, type AuthState } from "../../store/auth-context";
import { testUser } from "../../test/testUser";
import type { WorkspaceSummary } from "../../types/auth";
import type { DailyFormDefinition, DailyFormSubmission } from "../../types/dailyForm";
import type { DailyWorkflow, WorkspaceSettings } from "../../types/dailyWorkflow";
import { workspaceToday } from "../../utils/workspaceDate";
import { DailyWorkflowPage } from "./DailyWorkflowPage";

vi.mock("../../api/workspaceApi", () => ({ listWorkspaces: vi.fn() }));
vi.mock("../../api/dailyWorkflowApi", () => ({ evaluateDailyWorkflow: vi.fn(), getWorkspaceSettings: vi.fn() }));
vi.mock("../../api/dailyFormApi", () => ({ getDailyFormDefinition: vi.fn(), getDailyFormSubmission: vi.fn(), putDailyFormSubmission: vi.fn() }));

const workspace: WorkspaceSummary = { id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa", name: "Personal", description: null, timezone: "America/Lima", created_at: "2026-08-01T00:00:00Z", updated_at: "2026-08-01T00:00:00Z" };
const otherWorkspace = { ...workspace, id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb", name: "Trabajo", timezone: "Pacific/Kiritimati" };
const settings: WorkspaceSettings = { id: "10000000-0000-4000-8000-000000000000", workspace_id: workspace.id, timezone: workspace.timezone, daily_form_enabled: true, daily_form_reminder_time: "09:00:00", daily_task_generation_enabled: true, week_starts_on: "monday", created_at: "2026-08-01T00:00:00Z", updated_at: "2026-08-01T00:00:00Z" };
const definition: DailyFormDefinition = { id: "20000000-0000-4000-8000-000000000000", workspace_id: workspace.id, questions: [
  { id: "22000000-0000-4000-8000-000000000000", order: 2, title: "Comentario", description: null, answer_type: "text" },
  { id: "21000000-0000-4000-8000-000000000000", order: 1, title: "¿Cumpliste?", description: "Confirma el resultado", answer_type: "boolean" },
  { id: "23000000-0000-4000-8000-000000000000", order: 3, title: "Puntuación", description: null, answer_type: "number" }
], created_at: "2026-08-01T00:00:00Z", updated_at: "2026-08-01T00:00:00Z" };
const date = "2026-08-07";
const workflow: DailyWorkflow = { workspace_id: workspace.id, user_id: testUser.id, workflow_date: date, workflow_status: "ACTION_REQUIRED", form_required: true, form_submitted: false, definition_id: definition.id, submission_id: null, task_generation: { workspace_id: workspace.id, generation_date: date, eligible_series_count: 4, created_task_count: 2, skipped_existing_count: 2, created_task_ids: ["1", "2"], generated_at: "2026-08-07T13:00:00Z" }, evaluated_at: "2026-08-07T13:00:00Z" };
const submission: DailyFormSubmission = { id: "30000000-0000-4000-8000-000000000000", workspace_id: workspace.id, user_id: testUser.id, definition_id: definition.id, submission_date: date, answers: [
  { question_id: definition.questions[1].id, question_title: "¿Cumpliste?", question_order: 1, answer_type: "boolean", value: false },
  { question_id: definition.questions[0].id, question_title: "Comentario", question_order: 2, answer_type: "text", value: "Respuesta previa" },
  { question_id: definition.questions[2].id, question_title: "Puntuación", question_order: 3, answer_type: "number", value: 7.5 }
], created_at: "2026-08-07T13:00:00Z", updated_at: "2026-08-07T13:00:00Z" };

function Auth({ children, initial = workspace }: PropsWithChildren<{ initial?: WorkspaceSummary | null }>) { const [selected, setWorkspace] = useState(initial); const value = useMemo<AuthState>(() => ({ accessToken: "token", user: testUser, workspace: selected, isAuthenticated: true, isInitializing: false, login: vi.fn(), logout: vi.fn(), setWorkspace, clearSession: vi.fn() }), [selected]); return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>; }
function Switcher() { const { setWorkspace } = useAuth(); return <button onClick={() => setWorkspace(otherWorkspace)}>Cambiar espacio</button>; }
function renderPage(url = `/daily-workflow?date=${date}`, initial: WorkspaceSummary | null = workspace, switcher = false) { const client = new QueryClient({ defaultOptions: { queries: { retry: false, gcTime: Infinity }, mutations: { retry: false } } }); render(<QueryClientProvider client={client}><Auth initial={initial}><MemoryRouter initialEntries={[url]}>{switcher && <Switcher />}<DailyWorkflowPage /></MemoryRouter></Auth></QueryClientProvider>); return client; }

describe("DailyWorkflowPage", () => {
  beforeEach(() => { vi.clearAllMocks(); vi.mocked(workspaceApi.listWorkspaces).mockResolvedValue([workspace]); vi.mocked(workflowApi.getWorkspaceSettings).mockResolvedValue(settings); vi.mocked(workflowApi.evaluateDailyWorkflow).mockResolvedValue(workflow); vi.mocked(formApi.getDailyFormDefinition).mockResolvedValue(definition); vi.mocked(formApi.getDailyFormSubmission).mockResolvedValue(null); vi.mocked(formApi.putDailyFormSubmission).mockResolvedValue(submission); });

  it("derives Workspace-local today without using the UTC date", () => { expect(workspaceToday("America/Lima", new Date("2026-08-08T02:00:00Z"))).toBe("2026-08-07"); expect(workspaceToday("Pacific/Kiritimati", new Date("2026-08-08T02:00:00Z"))).toBe("2026-08-08"); });
  it("uses a valid URL date and safely falls back from an invalid date", async () => { renderPage(); await waitFor(() => expect(workflowApi.evaluateDailyWorkflow).toHaveBeenCalledWith(workspace.id, date)); expect(screen.getByLabelText("Fecha")).toHaveValue(date); });
  it("falls back to Workspace-local today for an invalid URL date", async () => { const expected = workspaceToday(workspace.timezone); renderPage("/daily-workflow?date=invalid"); await waitFor(() => expect(workflowApi.evaluateDailyWorkflow).toHaveBeenCalledWith(workspace.id, expected)); expect(screen.getByLabelText("Fecha")).toHaveValue(expected); });
  it("prevents all workflow calls without a Workspace", async () => { vi.mocked(workspaceApi.listWorkspaces).mockResolvedValue([]); renderPage("/daily-workflow", null); expect(await screen.findByText("No hay un espacio de trabajo disponible")).toBeInTheDocument(); expect(workflowApi.evaluateDailyWorkflow).not.toHaveBeenCalled(); expect(workflowApi.getWorkspaceSettings).not.toHaveBeenCalled(); });
  it("isolates evaluation on Workspace and date changes", async () => { vi.mocked(workspaceApi.listWorkspaces).mockResolvedValue([workspace, otherWorkspace]); const user = userEvent.setup(); renderPage(undefined, workspace, true); await waitFor(() => expect(workflowApi.evaluateDailyWorkflow).toHaveBeenCalledWith(workspace.id, date)); await user.click(screen.getByRole("button", { name: "Cambiar espacio" })); await waitFor(() => expect(workflowApi.evaluateDailyWorkflow).toHaveBeenCalledWith(otherWorkspace.id, date)); await user.click(screen.getByRole("button", { name: "Día siguiente" })); await waitFor(() => expect(workflowApi.evaluateDailyWorkflow).toHaveBeenCalledWith(otherWorkspace.id, "2026-08-08")); });
  it("renders ACTION_REQUIRED and real Task generation counts", async () => { renderPage(); expect(await screen.findByRole("heading", { name: "Acción requerida" })).toBeInTheDocument(); expect(screen.getByText("Se generaron 2 tareas recurrentes para este día.")).toBeInTheDocument(); expect(screen.getByText("Series elegibles").nextElementSibling).toHaveTextContent("4"); expect(screen.getByText("Ya existentes").nextElementSibling).toHaveTextContent("2"); });
  it("renders READY and repeated skipped generation safely", async () => { vi.mocked(workflowApi.evaluateDailyWorkflow).mockResolvedValue({ ...workflow, workflow_status: "READY", form_submitted: true, submission_id: submission.id, task_generation: { ...workflow.task_generation, created_task_count: 0, skipped_existing_count: 4 } }); renderPage(); expect(await screen.findByRole("heading", { name: "Listo" })).toBeInTheDocument(); expect(screen.getByText("No había tareas recurrentes nuevas para generar.")).toBeInTheDocument(); });
  it("shows disabled and no-definition product states", async () => { vi.mocked(workflowApi.getWorkspaceSettings).mockResolvedValue({ ...settings, daily_form_enabled: false }); vi.mocked(workflowApi.evaluateDailyWorkflow).mockResolvedValue({ ...workflow, workflow_status: "READY", form_required: false }); renderPage(); expect(await screen.findByText("Formulario desactivado")).toBeInTheDocument(); expect(formApi.getDailyFormDefinition).not.toHaveBeenCalled(); });
  it("treats missing definition and submission as valid states", async () => { vi.mocked(formApi.getDailyFormDefinition).mockResolvedValue(null); renderPage(); expect(await screen.findByText("No hay un formulario configurado")).toBeInTheDocument(); });

  it("orders questions and serializes boolean, text, and number values", async () => { const user = userEvent.setup(); renderPage(); expect(await screen.findByText("1. ¿Cumpliste?")).toBeInTheDocument(); const questions = screen.getAllByText(/^\d\./).map((element) => element.textContent); expect(questions.slice(0, 3)).toEqual(["1. ¿Cumpliste?", "2. Comentario", "3. Puntuación"]); await user.click(screen.getByLabelText("Sí")); await user.type(screen.getByLabelText("2. Comentario"), "Buen día"); await user.type(screen.getByLabelText("3. Puntuación"), "8.5"); await user.click(screen.getByRole("button", { name: "Enviar formulario" })); await waitFor(() => expect(formApi.putDailyFormSubmission).toHaveBeenCalledWith(workspace.id, date, { answers: [
    { question_id: definition.questions[1].id, value: true }, { question_id: definition.questions[0].id, value: "Buen día" }, { question_id: definition.questions[2].id, value: 8.5 }
  ] })); });
  it("requires every answer and preserves entered values after a failed save", async () => { vi.mocked(formApi.putDailyFormSubmission).mockRejectedValue({ isAxiosError: true, response: { status: 422 } }); const user = userEvent.setup(); renderPage(); await screen.findByText("1. ¿Cumpliste?"); await user.click(screen.getByRole("button", { name: "Enviar formulario" })); expect(await screen.findAllByRole("alert")).toHaveLength(3); await user.click(screen.getByLabelText("No")); await user.type(screen.getByLabelText("2. Comentario"), "Conservar"); await user.type(screen.getByLabelText("3. Puntuación"), "5"); await user.click(screen.getByRole("button", { name: "Enviar formulario" })); expect(await screen.findByText(/Revisa todas las respuestas/)).toBeInTheDocument(); expect(screen.getByLabelText("2. Comentario")).toHaveValue("Conservar"); });
  it("prefills and replaces an existing same-date submission", async () => { vi.mocked(formApi.getDailyFormSubmission).mockResolvedValue(submission); const user = userEvent.setup(); renderPage(); expect(await screen.findByText(/Formulario enviado/)).toBeInTheDocument(); expect(screen.getByLabelText("No")).toBeChecked(); expect(screen.getByLabelText("2. Comentario")).toHaveValue("Respuesta previa"); expect(screen.getByLabelText("3. Puntuación")).toHaveValue(7.5); await user.clear(screen.getByLabelText("2. Comentario")); await user.type(screen.getByLabelText("2. Comentario"), "Actualizada"); await user.click(screen.getByRole("button", { name: "Guardar cambios" })); await waitFor(() => expect(formApi.putDailyFormSubmission).toHaveBeenCalled()); expect(submission.id).toBe("30000000-0000-4000-8000-000000000000"); });
  it("re-evaluates after submission and invalidates only date-scoped submission data", async () => { const user = userEvent.setup(); const client = renderPage(); const invalidate = vi.spyOn(client, "invalidateQueries"); await screen.findByText("1. ¿Cumpliste?"); await waitFor(() => expect(workflowApi.evaluateDailyWorkflow).toHaveBeenCalledTimes(1)); vi.mocked(workflowApi.evaluateDailyWorkflow).mockResolvedValue({ ...workflow, workflow_status: "READY", form_submitted: true, submission_id: submission.id, task_generation: { ...workflow.task_generation, created_task_count: 0, skipped_existing_count: 4 } }); invalidate.mockClear(); await user.click(screen.getByLabelText("Sí")); await user.type(screen.getByLabelText("2. Comentario"), "Listo"); await user.type(screen.getByLabelText("3. Puntuación"), "10"); await user.click(screen.getByRole("button", { name: "Enviar formulario" })); await waitFor(() => expect(workflowApi.evaluateDailyWorkflow).toHaveBeenCalledTimes(2)); expect(invalidate).toHaveBeenCalledWith({ queryKey: ["daily-form", "submission", workspace.id, date] }); expect(invalidate).not.toHaveBeenCalledWith({ queryKey: ["tasks", workspace.id] }); });
  it("invalidates current Workspace Tasks and Dashboard only when generation creates Tasks", async () => { const client = renderPage(); const invalidate = vi.spyOn(client, "invalidateQueries"); await waitFor(() => expect(workflowApi.evaluateDailyWorkflow).toHaveBeenCalled()); await waitFor(() => expect(invalidate).toHaveBeenCalledWith({ queryKey: ["tasks", workspace.id] })); expect(invalidate).toHaveBeenCalledWith({ queryKey: ["dashboard", "summary", workspace.id] }); expect(invalidate).not.toHaveBeenCalledWith({ queryKey: ["tasks", otherWorkspace.id] }); });
  it("supports previous, next, Today, and manual refresh controls", async () => { const user = userEvent.setup(); renderPage(); await waitFor(() => expect(workflowApi.evaluateDailyWorkflow).toHaveBeenCalledWith(workspace.id, date)); await user.click(screen.getByRole("button", { name: "Día anterior" })); await waitFor(() => expect(workflowApi.evaluateDailyWorkflow).toHaveBeenCalledWith(workspace.id, "2026-08-06")); await user.click(screen.getByRole("button", { name: "Día siguiente" })); await user.click(screen.getByRole("button", { name: "Actualizar" })); await waitFor(() => expect(vi.mocked(workflowApi.evaluateDailyWorkflow).mock.calls.length).toBeGreaterThanOrEqual(3)); });
});
